aot_table_top – Aotus
aot_table_top Function
10 statements
Source File
public function aot_table_top(L) result(thandle)
Return the position at the top of the stack as a table handle.
If it actually exists and is a table, this handle can be used for further operations on that table. Otherwise a 0 will be returned.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
Return Value integer
A handle for the table on the top of the stack to access it.
Calls
Called by
Source Code
  function aot_table_top(L) result(thandle)
    type(flu_state) :: L !! Handle for the Lua script.
    !> A handle for the table on the top of the stack to access it.
    integer :: thandle
    if (.not. flu_isTable(L, -1)) then
      thandle = 0
      call flu_pop(L)
    else
      thandle = flu_gettop(L)
    end if
  end function aot_table_top
Call graph
aot_table_top calls flu_gettop, flu_istable, flu_pop
flu_gettop calls lua_gettop
flu_istable calls lua_type
flu_pop calls lua_settop
aot_table_open calls aot_table_top
get_top_double_v calls aot_table_top
get_top_double_vvect calls aot_table_top
get_top_extdouble_v calls aot_table_top
get_top_extdouble_vvect calls aot_table_top
get_top_integer_v calls aot_table_top
get_top_integer_vvect calls aot_table_top
get_top_logical_v calls aot_table_top
get_top_logical_vvect calls aot_table_top
get_top_long_v calls aot_table_top
get_top_long_vvect calls aot_table_top
get_top_quadruple_v calls aot_table_top
get_top_quadruple_vvect calls aot_table_top
get_top_real_v calls aot_table_top
get_top_real_vvect calls aot_table_top
get_top_string_v calls aot_table_top
get_top_string_vvect calls aot_table_top
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v, get_top_extdouble_vvect, get_top_extdouble_v
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table