aot_type_of – Aotus
aot_type_of Function
17 statements
Source File
public function aot_type_of(L, thandle, key, pos) result(luatype)
Get the Lua object in table thandle under the given key or pos on the top of the stack and return the Lua type of the gotten entry.
This might be used to get a Lua entry to the top of the stack without knowing its type beforehand, and then deciding what to load, based on the type. Lua types are encoded as integer values and available in the flu_binding module.
FLU_TNONE : not existing
FLU_TNIL : not available
FLU_TBOOLEAN : logical value
FLU_TNUMBER : a number
FLU_TSTRING : a string
FLU_TTABLE : a table
FLU_TFUNCTION: a function
If none of key, pos or thandle are provided, the type of the current top of the stack will be returned. Just passing pos without a thandle is invalid and always returns FLU_TNONE.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle of the table to get the value from
character(len=*), intent(in), optional :: key
Key of the value to find the type for.
integer, intent(in), optional :: pos
Position of the value to find the type for.
Return Value integer
Type of the Lua object found in L, thandle, key and pos
Calls
Called by
Source Code
  function aot_type_of(L, thandle, key, pos) result(luatype)
    type(flu_State) :: L !! Handle to the Lua script.
    !> Handle of the table to get the value from
    integer, intent(in), optional :: thandle
    !> Key of the value to find the type for.
    character(len=*), intent(in), optional :: key
    !> Position of the value to find the type for.
    integer, intent(in), optional :: pos
    !> Type of the Lua object found in L, thandle, key and pos
    integer :: luatype
    luatype = FLU_TNONE
    if (present(thandle)) then
      call aot_table_push( L       = L,       &
        &                  thandle = thandle, &
        &                  key     = key,     &
        &                  pos     = pos,     &
        &                  toptype = luatype  )
    else
      if (present(key)) then
        luatype = flu_getglobal(L, key)
      else if (.not. present(pos)) then
        luatype = flu_type(L, -1)
      end if
    end if
  end function aot_type_of
Call graph
aot_type_of calls aot_table_push, flu_getglobal, flu_type
aot_table_push calls flu_getglobal, flu_type, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil
flu_getglobal calls lua_getglobal
flu_type calls lua_type
flu_pushinteger calls flu_pushint, flu_pushlong
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
get_table_double_v calls aot_type_of
get_table_double_vvect calls aot_type_of
get_table_integer_v calls aot_type_of
get_table_integer_vvect calls aot_type_of
get_table_logical_v calls aot_type_of
get_table_logical_vvect calls aot_type_of
get_table_long_v calls aot_type_of
get_table_long_vvect calls aot_type_of
get_table_real_v calls aot_type_of
get_table_real_vvect calls aot_type_of
get_table_string_v calls aot_type_of
get_table_string_vvect calls aot_type_of
aot_get_val calls get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_table_get_val calls get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v