aot_path_close_fun – Aotus
aot_path_close_fun Subroutine
8 statements
Source File
private subroutine aot_path_close_fun(me, conf, fun, closeLua)
This routine closes function and all other tables opened along the path.
Arguments
Type Intent Optional Attributes Name
type(aot_path_type), intent(inout) :: me
The path object to open as a function
type(flu_State) :: conf
The flu_state handle, which is either opened according to the path, or used to open the path in.
type(aot_fun_type), intent(inout) :: fun
The opened function
logical, intent(in), optional :: closeLua
A flag to indicate, wether to close the Lua script, default is false.
Calls
Called by
Source Code
  subroutine aot_path_close_fun(me, conf, fun, closeLua)
    !> The path object to open as a function
    type(aot_path_type), intent(inout) :: me
    !> The flu_state handle, which is either opened according to
    !! the path, or used to open the path in.
    type(flu_state) :: conf
    !> The opened function
    type(aot_fun_type), intent(inout) :: fun
    !> A flag to indicate, wether to close the Lua script, default
    !! is false.
    logical, intent(in), optional :: closeLua
    ! close function
    call aot_fun_close(L=conf, fun=fun)
    ! close tables
    call aot_path_close_table( me, conf, closeLua )
  end subroutine aot_path_close_fun
Call graph
aot_path_close_fun calls aot_fun_close, aot_path_close_table
aot_fun_close calls flu_settop
aot_path_close_table calls aot_table_close, close_config
aot_table_close calls flu_settop
close_config calls flu_close
flu_settop calls lua_settop
flu_close calls lua_close
aot_path_close calls aot_path_close_fun