aot_path_close_table – Aotus
aot_path_close_table Subroutine
13 statements
Source File
private subroutine aot_path_close_table(me, conf, closeLua)
This routine closes all the table opened in aot_path_open_table.
Arguments
Type Intent Optional Attributes Name
type(aot_path_type), intent(inout) :: me
The path object to open as a function
type(flu_State) :: conf
The flu_state handle, which is either opened according to the path, or used to open the path in.
logical, intent(in), optional :: closeLua
A flag to indicate, wether to close the Lua script, default is false.
Calls
Called by
Source Code
  subroutine aot_path_close_table(me, conf, closeLua)
    !> The path object to open as a function
    type(aot_path_type), intent(inout) :: me
    !> The flu_state handle, which is either opened according to
    !! the path, or used to open the path in.
    type(flu_state) :: conf
    !> A flag to indicate, wether to close the Lua script, default
    !! is false.
    logical, intent(in), optional :: closeLua
    if (me%roothandle /= 0) then
      call aot_table_close(L=conf, thandle=me%roothandle)
    end if
    if (present(closeLua)) then
      if (closeLua) then
        call close_config(conf)
      end if
    end if
  end subroutine aot_path_close_table
Call graph
aot_path_close_table calls aot_table_close, close_config
aot_table_close calls flu_settop
close_config calls flu_close
flu_close calls lua_close
flu_settop calls lua_settop
aot_path_close calls aot_path_close_table, aot_path_close_fun
aot_path_close_fun calls aot_path_close_table