aot_reference_to_top – Aotus
aot_reference_to_top Subroutine
6 statements
Source File
public subroutine aot_reference_to_top(L, ref)
Put a given reference (ref) in the Lua script (L) to the top of the stack.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle to the Lua script
integer :: ref
Reference retrieved by aot_reference_for to put on the top of the stack
Calls
Called by
Source Code
  subroutine aot_reference_to_top(L, ref)
    type(flu_State) :: L !! Handle to the Lua script
    !> Reference retrieved by [[aot_reference_for]] to put on the top
    !! of the stack
    integer :: ref
    integer :: luatype
    luatype = flu_rawgeti(L, LUA_REGISTRYINDEX, ref)
  end subroutine aot_reference_to_top
Call graph
aot_reference_to_top calls flu_rawgeti
flu_rawgeti calls lua_rawgeti
aot_fun_ref calls aot_reference_to_top
aot_fun_open calls aot_fun_ref
aot_path_open_fun calls aot_fun_open
aot_path_open calls aot_path_open_fun