aot_table_set_top – Aotus
aot_table_set_top Subroutine
19 statements
Source File
public subroutine aot_table_set_top(L, thandle, key, pos)
Put the top of the stack into a table.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Key and pos are both optional, however at least one of them has to be supplied. The key takes precedence over the pos if both are given.
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
It allows the access to unnamed arrays in the Lua tables.
Calls
Source Code
  subroutine aot_table_set_top(L, thandle, key, pos)
    type(flu_State) :: L !! Handle to the Lua script.
    !> Handle to the table to look the value up in.
    integer, intent(in) :: thandle
    !> Name of the entry to look for.
    !!
    !! Key and pos are both optional, however at least one of them has to be
    !! supplied.
    !! The key takes precedence over the pos if both are given.
    character(len=*), intent(in), optional :: key
    !> Position of the entry to look for in the table.
    !!
    !! It allows the access to unnamed arrays in the Lua tables.
    integer, intent(in), optional :: pos
    integer :: indpos
    ! First store the current top of the stack for later reference, to
    ! move the desired position infront of it.
    indpos = flu_gettop(L)
    ! Only put the top into the given table, if it is a valid reference,
    ! and the top is not the table itself.
    if ( (thandle > 0) .and. (thandle < indpos) ) then
      if (present(key)) then
        ! There is a key, given, use it to put the value into the table.
        call flu_setField(L, thandle, trim(key))
      else
        ! No key given, try to put the value by position
        if (present(pos)) then
          ! First put the index, where to write the value into the table, on the
          ! stack.
          call flu_pushInteger(L, pos)
          ! Now move this position infront of the actual argument, which was
          ! at the top previously.
          call flu_insert(L, indpos)
          ! Use the two entries from the stack to put the value at the given
          ! position into the table.
          call flu_setTable(L, thandle)
        end if
      end if
    end if
  end subroutine aot_table_set_top
Call graph
aot_table_set_top calls flu_pushinteger, flu_gettop, flu_insert, flu_setfield, flu_settable
flu_pushinteger calls flu_pushint, flu_pushlong
flu_gettop calls lua_gettop
flu_insert calls lua_rotate
flu_setfield calls lua_setfield
flu_settable calls lua_settable
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger