aot_table_push – Aotus
aot_table_push Subroutine
45 statements
Source File
public subroutine aot_table_push(L, thandle, key, pos, toptype)
This subroutine tries to push the value of the entry given by key or pos within the table thandle onto the Lua stack.
If no corresponding value is found, a nil value is pushed to the stack. Key, pos and thandle are all optional. If no thandle is provided, the key will be obtained as a global variable. When none of thandle, key and pos are provided, the subroutine does nothing and the resulting type returned in toptype is the type of the current top entry in the Lua stack. Passing only pos without thandle is illegal and will result in a NIL value on the top of the stack.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look in.
character(len=*), intent(in), optional :: key
Name of the entry to push to the stack.
integer, intent(in), optional :: pos
Position of the entry to push to the stack.
integer, intent(out), optional :: toptype
Calls
Called by
Source Code
  subroutine aot_table_push(L, thandle, key, pos, toptype)
    type(flu_state) :: L !! Handle for the Lua script.
    !> Handle to the table to look in.
    integer, intent(in), optional :: thandle
    !> Name of the entry to push to the stack.
    character(len=*), intent(in), optional :: key
    !> Position of the entry to push to the stack.
    integer, intent(in), optional :: pos
    integer, intent(out), optional :: toptype
    integer :: loctype
    loctype = FLU_TNIL
    istable: if (present(thandle)) then
      if (thandle /= 0) then
        ! Only proceed if thandle is actually a table
        ! (Should be received with aot_table_global or aot_table_top)
        if (present(key)) then
          ! Try to look up the given key first
          loctype = flu_getfield(L, thandle, key)
          if ((loctype == FLU_TNONE) .or. (loctype == FLU_TNIL)) then
            ! If this is not found, try to retrieve
            ! the value at the given position
            if (present(pos)) then
              call flu_pop(L)
              call flu_pushInteger(L, pos)
              loctype = flu_getTable(L, thandle)
            end if
          end if
        else
          ! No key to look up, just check the given position
          if (present(pos)) then
            call flu_pushInteger(L, pos)
            loctype = flu_getTable(L, thandle)
          else
            ! Neither key nor pos present, nothing to look up
            ! Just push a NIL onto the stack as a result
            call flu_pushnil(L)
          end if
        end if
      else
        call flu_pushnil(L)
      end if
    else istable
      if (present(key)) then
        ! Try to look up the given key as a global variable
        loctype = flu_getglobal(L, key)
      else
        ! No key, no thandle, treat this as a no-op if also no pos is provided
        ! and return the type of the current top of the Lua stack.
        if (present(pos)) then
          ! Passing pos without thandle is illegal, and we always push a NIL
          ! in this case.
          call flu_pushnil(L)
        else
          loctype = flu_type(L, -1)
        end if
      end if
    end if istable
    if (present(toptype)) then
      toptype = loctype
    end if
  end subroutine aot_table_push
Call graph
aot_table_push calls flu_pushinteger, flu_getfield, flu_getglobal, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_pushinteger calls flu_pushint, flu_pushlong
flu_getfield calls lua_getfield
flu_getglobal calls lua_getglobal
flu_gettable calls lua_gettable
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_type calls lua_type
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
aot_push calls aot_table_push
aot_exists calls aot_table_push
aot_fun_table calls aot_table_push
aot_reference_for calls aot_table_push
aot_table_open calls aot_table_push
aot_type_of calls aot_table_push
get_table_double calls aot_table_push
get_table_extdouble calls aot_table_push
get_table_extdouble_v calls aot_table_push
get_table_extdouble_vvect calls aot_table_push
get_table_integer calls aot_table_push
get_table_logical calls aot_table_push
get_table_long calls aot_table_push
get_table_quadruple calls aot_table_push
get_table_quadruple_v calls aot_table_push
get_table_quadruple_vvect calls aot_table_push
get_table_real calls aot_table_push
get_table_string calls aot_table_push
get_table_userdata calls aot_table_push
aot_fun_open calls aot_fun_table
aot_get_val calls get_table_quadruple_vvect, get_table_quadruple_v, get_table_extdouble_vvect, get_table_extdouble_v, get_table_extdouble, get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_quadruple, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_table_get_val calls get_table_quadruple_vvect, get_table_quadruple_v, get_table_extdouble_vvect, get_table_extdouble_v, get_table_extdouble, get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_quadruple, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
get_table_double_v calls aot_type_of
get_table_double_vvect calls aot_type_of
get_table_integer_v calls aot_type_of
get_table_integer_vvect calls aot_type_of
get_table_logical_v calls aot_type_of
get_table_logical_vvect calls aot_type_of
get_table_long_v calls aot_type_of
get_table_long_vvect calls aot_type_of
get_table_real_v calls aot_type_of
get_table_real_vvect calls aot_type_of
get_table_string_v calls aot_type_of
get_table_string_vvect calls aot_type_of
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_fun_open, aot_path_open_table