aot_top_get_logical – Aotus
aot_top_get_logical Subroutine
29 statements
Source File
private subroutine aot_top_get_logical(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a single precision real.
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
logical, intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
Calls
Called by
Source Code
  subroutine aot_top_get_logical(val, ErrCode, L, default)
    type(flu_State) :: L !! Handle to the Lua script
    !> Value of the Variable in the script
    logical, intent(out) :: val
    !> Error code to indicate what kind of problem might have occured.
    integer, intent(out) :: ErrCode
    !> Some default value, that should be used, if the variable is not set in
    !! the Lua script.
    logical, optional, intent(in) :: default
    logical :: not_retrievable
    ErrCode = 0
    not_retrievable = .false.
    if (flu_isNoneOrNil(L, -1)) then
      ErrCode = ibSet(ErrCode, aoterr_NonExistent)
      not_retrievable = .true.
    else
      if (flu_isBoolean(L, -1)) then
        val = flu_toBoolean(L, -1)
      else
        ErrCode = ibSet(ErrCode, aoterr_WrongType)
        ErrCode = ibSet(ErrCode, aoterr_Fatal)
        not_retrievable = .true.
      end if
    end if
    if (not_retrievable) then
      if (present(default)) then
        val = default
      else
        ErrCode = ibSet(ErrCode, aoterr_Fatal)
      end if
    end if
    call flu_pop(L)
  end subroutine aot_top_get_logical
Call graph
aot_top_get_logical calls flu_isboolean, flu_isnoneornil, flu_pop, flu_toboolean
flu_isboolean calls lua_type
flu_isnoneornil calls lua_type
flu_pop calls lua_settop
flu_toboolean calls lua_toboolean
aot_top_get_val calls aot_top_get_logical