aot_require_buffer – Aotus
aot_require_buffer Subroutine
13 statements
Source File
public subroutine aot_require_buffer(L, buffer, modname)
Load and execute a given buffer and register it in the package table as the given module name.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Lua State to set load the buffer into.
character(len=1), intent(in) :: buffer(:)
Buffer to load.
character(len=*), intent(in) :: modname
Module name to set.
Calls
Source Code
  subroutine aot_require_buffer(L, buffer, modname)
    type(flu_State) :: L !! Lua State to set load the buffer into.
    character, intent(in) :: buffer(:) !! Buffer to load.
    character(len=*), intent(in) :: modname !! Module name to set.
    integer :: pac_handle
    integer :: ld_handle
    call open_config_buffer(L = L, buffer = buffer, bufName = trim(modname))
    call aot_table_open(L, thandle = pac_handle, key = "package")
    call aot_table_open(L, parent = pac_handle, &
      &                 thandle = ld_handle, key = "loaded")
    call aot_table_set_val(val = .true., L = L, thandle = ld_handle, &
      &                    key = trim(modname))
    call aot_table_close(L, ld_handle)
    call aot_table_close(L, pac_handle)
  end subroutine aot_require_buffer
Call graph
aot_require_buffer calls aot_table_set_val, aot_table_close, aot_table_open, open_config_buffer
aot_table_set_val calls set_table_extdouble
aot_table_close calls flu_settop
aot_table_open calls aot_table_push, aot_table_top, flu_createtable, flu_getglobal, flu_gettop
open_config_buffer calls aot_err_handler, flu_isopen, flu_pcall, flul_loadbuffer, flul_newstate, flul_openlibs
aot_err_handler calls flu_tolstring
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
aot_table_top calls flu_gettop, flu_istable, flu_pop
flu_createtable calls lua_createtable
flu_getglobal calls lua_getglobal
flu_gettop calls lua_gettop
flu_pcall calls lua_pcallk
flu_settop calls lua_settop
flul_loadbuffer calls lual_loadbufferx
flul_newstate calls lual_newstate
flul_openlibs calls lual_openlibs
set_table_extdouble calls flu_pushinteger, flu_pushnumber, flu_setfield, flu_settable
flu_pushinteger calls flu_pushint, flu_pushlong
flu_pushnumber calls flu_pushdouble, flu_pushreal
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_istable calls lua_type
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_setfield calls lua_setfield
flu_settable calls lua_settable
flu_tolstring calls lua_tolstring
flu_type calls lua_type
flu_pushdouble calls lua_pushnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_pushreal calls lua_pushnumber