aot_table_open – Aotus
aot_table_open Subroutine
21 statements
Source File
public subroutine aot_table_open(L, parent, thandle, key, pos)
This subroutine tries to open a table, and returns a handle for it.
If parent is present, the table is tried to open within that table. Return its position in the stack as a handle for this table. If it does not exist or the table entry is not a table itself, the handle will be set to 0. The table can be looked up either by position or name.
If a key is present but no parent, a global table is opened. If neither key nor parent is present, a new table is created. Only passing pos, without a thandle is erroneous and always results in a thandle = 0.
After the table is opened, the returned handle can be used to access its components.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
integer, intent(in), optional :: parent
Handle of the table containing the requested table.
integer, intent(out) :: thandle
A handle for the table to access it, 0 if no table available.
character(len=*), intent(in), optional :: key
Name of the entry in the parent table to access.
The key takes precedence over the position, if both are provided. In this case the positional address is only tried, if the access to the key failed.
integer, intent(in), optional :: pos
Position of the entry in the parent table to access.
Calls
Called by
Source Code
  subroutine aot_table_open(L, parent, thandle, key, pos)
    type(flu_state) :: L !! Handle for the Lua script.
    !> Handle of the table containing the requested table.
    integer, intent(in), optional :: parent
    !> A handle for the table to access it, 0 if no table available.
    integer, intent(out) :: thandle
    !> Name of the entry in the parent table to access.
    !!
    !! The key takes precedence over the position, if both are provided.
    !! In this case the positional address is only tried, if the access to the
    !! key failed.
    character(len=*), intent(in), optional :: key
    !> Position of the entry in the parent table to access.
    integer, intent(in), optional :: pos
    integer :: luatype
    thandle = 0
    if (present(parent)) then
      call aot_table_push(L, parent, key, pos)
      thandle = aot_table_top(L)
    else
      if (present(key)) then
        luatype = flu_getglobal(L, key)
        thandle = aot_table_top(L)
      else if (.not. present(pos)) then
        call flu_createtable(L, 0, 0)
        thandle = flu_gettop(L)
      end if
    end if
  end subroutine aot_table_open
Call graph
aot_table_open calls aot_table_push, aot_table_top, flu_createtable, flu_getglobal, flu_gettop
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
aot_table_top calls flu_gettop, flu_istable, flu_pop
flu_createtable calls lua_createtable
flu_getglobal calls lua_getglobal
flu_gettop calls lua_gettop
flu_pushinteger calls flu_pushint, flu_pushlong
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_istable calls lua_type
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_type calls lua_type
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table