aot_top_get_extdouble – Aotus
aot_top_get_extdouble Subroutine
29 statements
Source File
private subroutine aot_top_get_extdouble(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a extdouble precision real.
NOTE that numbers provided by Lua are only double precision.
Arguments
Type Intent Optional Attributes Name
real(kind=xdble_k), intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
real(kind=xdble_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
Calls
Called by
Source Code
  subroutine aot_top_get_extdouble(val, ErrCode, L, default)
    type(flu_State) :: L !< Handle to the Lua script
    !> Value of the Variable in the script
    real(kind=xdble_k), intent(out) :: val
    !> Error code to indicate what kind of problem might have occured.
    integer, intent(out) :: ErrCode
    !> Some default value, that should be used, if the variable is not set in
    !! the Lua script.
    real(kind=xdble_k), optional, intent(in) :: default
    logical :: not_retrievable
    ErrCode = 0
    not_retrievable = .false.
    if (flu_isNoneOrNil(L, -1)) then
      ErrCode = ibSet(ErrCode, aoterr_NonExistent)
      not_retrievable = .true.
    else
      if (flu_isNumber(L, -1)) then
        val = real(flu_toDouble(L, -1), kind=xdble_k)
      else
        ErrCode = ibSet(ErrCode, aoterr_WrongType)
        ErrCode = ibSet(ErrCode, aoterr_Fatal)
        not_retrievable = .true.
      end if
    end if
    if (not_retrievable) then
      if (present(default)) then
        val = default
      else
        ErrCode = ibSet(ErrCode, aoterr_Fatal)
      end if
    end if
    call flu_pop(L)
  end subroutine aot_top_get_extdouble
Call graph
aot_top_get_extdouble calls flu_isnoneornil, flu_isnumber, flu_pop, flu_todouble
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_pop calls lua_settop
flu_todouble calls lua_tonumberx
aot_top_get_val calls aot_top_get_extdouble, get_top_quadruple_vvect, get_top_quadruple_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v, get_top_extdouble_vvect, get_top_extdouble_v
get_table_double calls aot_top_get_val
get_table_double_v calls aot_top_get_val
get_table_double_vvect calls aot_top_get_val
get_table_extdouble calls aot_top_get_val
get_table_extdouble_v calls aot_top_get_val
get_table_extdouble_vvect calls aot_top_get_val
get_table_integer calls aot_top_get_val
get_table_integer_v calls aot_top_get_val
get_table_integer_vvect calls aot_top_get_val
get_table_logical calls aot_top_get_val
get_table_logical_v calls aot_top_get_val
get_table_logical_vvect calls aot_top_get_val
get_table_long calls aot_top_get_val
get_table_long_v calls aot_top_get_val
get_table_long_vvect calls aot_top_get_val
get_table_quadruple calls aot_top_get_val
get_table_quadruple_v calls aot_top_get_val
get_table_quadruple_vvect calls aot_top_get_val
get_table_real calls aot_top_get_val
get_table_real_v calls aot_top_get_val
get_table_real_vvect calls aot_top_get_val
get_table_string calls aot_top_get_val
get_table_string_v calls aot_top_get_val
get_table_string_vvect calls aot_top_get_val
get_table_userdata calls aot_top_get_val
get_top_double_v calls aot_top_get_val
get_top_double_vvect calls aot_top_get_val
get_top_extdouble_v calls aot_top_get_val
get_top_extdouble_vvect calls aot_top_get_val
get_top_integer_v calls aot_top_get_val
get_top_integer_vvect calls aot_top_get_val
get_top_logical_v calls aot_top_get_val
get_top_logical_vvect calls aot_top_get_val
get_top_long_v calls aot_top_get_val
get_top_long_vvect calls aot_top_get_val
get_top_quadruple_v calls aot_top_get_val
get_top_quadruple_vvect calls aot_top_get_val
get_top_real_v calls aot_top_get_val
get_top_real_vvect calls aot_top_get_val
get_top_string_v calls aot_top_get_val
get_top_string_vvect calls aot_top_get_val
aot_get_val calls get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_quadruple_vvect, get_table_quadruple_v, get_table_quadruple, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v, get_table_extdouble_vvect, get_table_extdouble_v, get_table_extdouble
aot_table_get_val calls get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_quadruple_vvect, get_table_quadruple_v, get_table_quadruple, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v, get_table_extdouble_vvect, get_table_extdouble_v, get_table_extdouble