aot_path_open_table – Aotus
aot_path_open_table Subroutine
40 statements
Source File
private subroutine aot_path_open_table(me, conf, thandle, openLua)
This subroutine opens all the tables on the way to the final head node of the given path.
The handle can be either passed in, to be used for the look up of the path, or, when specifying the optional openLua argument as true, it will return the handle to the newly opened Lua script.
Arguments
Type Intent Optional Attributes Name
type(aot_path_type), intent(inout) :: me
The path object to open as a function
type(flu_State) :: conf
The flu_state handle, which is either opened according to the path, or used to open the path in.
integer, intent(out) :: thandle
return handle of the last opened table
logical, intent(in), optional :: openLua
A flag to indicate, wether to open the Lua script, default is false, in which case the conf argument has to link to an actual Lua state handle.
Calls
Called by
Source Code
  subroutine aot_path_open_table(me, conf, thandle, openLua)
    !> The path object to open as a function
    type(aot_path_type), intent(inout) :: me
    !> The flu_state handle, which is either opened according to
    !! the path, or used to open the path in.
    type(flu_state) :: conf
    !> return handle of the last opened table
    integer, intent(out) :: thandle
    !> A flag to indicate, wether to open the Lua script, default
    !! is false, in which case the conf argument has to link to
    !! an actual Lua state handle.
    logical, intent(in), optional :: openLua
    logical :: new_conf
    type(aot_path_node_type), pointer :: curNode => NULL()
    integer :: myHandle = 0
    integer :: prevHandle = -1
    if (present(openLua)) then
      new_conf = openLua
    else
      new_conf = .false.
    end if
    if (new_conf) then
      call open_config_file(conf, me%LuaFilename)
    end if
    curNode => me%GlobalNode
    if (curNode%NodeType == 'table') then
      select case(curNode%ID_kind)
      case('key')
        call aot_table_open(L=conf, thandle=me%roothandle, key=curNode%key)
      end select
      if (associated(curNode%child)) then
        curNode => curNode%child
        myHandle = me%rootHandle
      end if
    end if
    do while(associated(curNode%child))
      prevHandle = myHandle
      select case(curNode%ID_kind)
      case('key')
        call aot_table_open(L=conf, thandle=myHandle, parent=prevHandle, &
          &                 key=curNode%key)
      case('position')
        call aot_table_open(L=conf, thandle=myHandle, parent=prevHandle, &
          &                 pos=curNode%pos)
      end select
      curNode => curNode%child
    end do
    thandle = myHandle
  end subroutine aot_path_open_table
Call graph
aot_path_open_table calls aot_table_open, open_config_file
aot_table_open calls aot_table_push, aot_table_top, flu_createtable, flu_getglobal, flu_gettop
open_config_file calls flu_dump, aot_err_handler, flu_isopen, flu_pcall, flul_loadfile, flul_newstate, flul_openlibs
flu_dump calls flu_dump_tobuf
aot_err_handler calls flu_tolstring
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
aot_table_top calls flu_gettop, flu_istable, flu_pop
flu_createtable calls lua_createtable
flu_getglobal calls lua_getglobal
flu_gettop calls lua_gettop
flu_pcall calls lua_pcallk
flul_loadfile calls lual_loadfilex
flul_newstate calls lual_newstate
flul_openlibs calls lual_openlibs
flu_pushinteger calls flu_pushint, flu_pushlong
flu_dump_tobuf calls dump_lua_tobuf
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_istable calls lua_type
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_tolstring calls lua_tolstring
flu_type calls lua_type
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table