aot_top_get_long – Aotus
aot_top_get_long Subroutine
29 statements
Source File
private subroutine aot_top_get_long(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a single precision real.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
integer(kind=long_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
Calls
Called by
Source Code
  subroutine aot_top_get_long(val, ErrCode, L, default)
    type(flu_State) :: L !! Handle to the Lua script
    !> Value of the Variable in the script
    integer(kind=long_k), intent(out) :: val
    !> Error code to indicate what kind of problem might have occured.
    integer, intent(out) :: ErrCode
    !> Some default value, that should be used, if the variable is not set in
    !! the Lua script.
    integer(kind=long_k), optional, intent(in) :: default
    logical :: not_retrievable
    ErrCode = 0
    not_retrievable = .false.
    if (flu_isNoneOrNil(L, -1)) then
      ErrCode = ibSet(ErrCode, aoterr_NonExistent)
      not_retrievable = .true.
    else
      if (flu_isNumber(L, -1)) then
        val = int(flu_toDouble(L, -1),kind=long_k)
      else
        ErrCode = ibSet(ErrCode, aoterr_WrongType)
        ErrCode = ibSet(ErrCode, aoterr_Fatal)
        not_retrievable = .true.
      end if
    end if
    if (not_retrievable) then
      if (present(default)) then
        val = default
      else
        ErrCode = ibSet(ErrCode, aoterr_Fatal)
      end if
    end if
    call flu_pop(L)
  end subroutine aot_top_get_long
Call graph
aot_top_get_long calls flu_isnoneornil, flu_isnumber, flu_pop, flu_todouble
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_pop calls lua_settop
flu_todouble calls lua_tonumberx
aot_top_get_val calls aot_top_get_long