aot_fun_table – Aotus
aot_fun_table Subroutine
9 statements
Source File
private subroutine aot_fun_table(L, parent, fun, key, pos)
Get a function defined as component of a table.
Functions in tables might be retrieved by position or key. If both optional parameters are provided, the key is attempted to be read first. Only when that fails, the position will be tested.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
integer, intent(in), optional :: parent
Handle to the table to look in for the function.
type(aot_fun_type), intent(out) :: fun
Returned handle, providing access to the function.
character(len=*), intent(in), optional :: key
Name of the function to look up in the table.
integer, intent(in), optional :: pos
Position of the function to look up in the table.
Calls
Called by
Source Code
  subroutine aot_fun_table(L, parent, fun, key, pos)
    type(flu_state) :: L !! Handle for the Lua script.
    !> Handle to the table to look in for the function.
    integer, intent(in), optional :: parent
    !> Returned handle, providing access to the function.
    type(aot_fun_type), intent(out) :: fun
    !> Name of the function to look up in the table.
    character(len=*), intent(in), optional :: key
    !> Position of the function to look up in the table.
    integer, intent(in), optional :: pos
    call aot_table_push(L, parent, key, pos)
    fun = aot_fun_top(L)
  end subroutine aot_fun_table
Call graph
aot_fun_table calls aot_fun_top, aot_table_push
aot_fun_top calls flu_gettop, flu_isfunction, flu_pushvalue, flu_topointer
aot_table_push calls flu_pushinteger, flu_getfield, flu_getglobal, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_pushinteger calls flu_pushint, flu_pushlong
flu_getfield calls lua_getfield
flu_getglobal calls lua_getglobal
flu_gettable calls lua_gettable
flu_gettop calls lua_gettop
flu_isfunction calls lua_type
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_pushvalue calls lua_pushvalue
flu_topointer calls lua_topointer
flu_type calls lua_type
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
aot_fun_open calls aot_fun_table
aot_path_open_fun calls aot_fun_open
aot_path_open calls aot_path_open_fun