aot_table_length – Aotus
aot_table_length Function
13 statements
Source File
public function aot_table_length(L, thandle) result(length)
Count the entries in a lua table.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
integer, intent(in) :: thandle
Handle of the table to count the enries in.
Return Value integer
Returns the number of entries in the table.
Calls
Called by
Source Code
  function aot_table_length(L, thandle) result(length)
    type(flu_state) :: L !! Handle for the Lua script.
    !> Handle of the table to count the enries in.
    integer, intent(in) :: thandle
    !> Returns the number of entries in the table.
    integer :: length
    length = 0
    if (aot_table_first(L, thandle)) then
      do
        length = length + 1
        call flu_pop(L)
        if (.not. flu_next(L, thandle)) exit
      end do
    end if
  end function aot_table_length
Call graph
aot_table_length calls aot_table_first, flu_next, flu_pop
aot_table_first calls flu_next, flu_pushnil
flu_next calls lua_next
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
get_top_double_v calls aot_table_length
get_top_double_vvect calls aot_table_length
get_top_extdouble_v calls aot_table_length
get_top_extdouble_vvect calls aot_table_length
get_top_integer_v calls aot_table_length
get_top_integer_vvect calls aot_table_length
get_top_logical_v calls aot_table_length
get_top_logical_vvect calls aot_table_length
get_top_long_v calls aot_table_length
get_top_long_vvect calls aot_table_length
get_top_quadruple_v calls aot_table_length
get_top_quadruple_vvect calls aot_table_length
get_top_real_v calls aot_table_length
get_top_real_vvect calls aot_table_length
get_top_string_v calls aot_table_length
get_top_string_vvect calls aot_table_length
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v, get_top_extdouble_vvect, get_top_extdouble_v