aot_table_first – Aotus
aot_table_first Function
11 statements
Source File
public function aot_table_first(L, thandle) result(exists)
Load the first key-value pair of table thandle on the stack.
This serves as an entry point, further traversal can be done by flu_next(L, thandle). If there are no entries in the table the function returns false, otherwise the result will be true.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
integer, intent(in) :: thandle
Handle to the table to get the first entry of.
Return Value logical
The return value signals, if there actually is such a first entry.
Calls
Called by
Source Code
  function aot_table_first(L, thandle) result(exists)
    type(flu_state) :: L !! Handle for the Lua script.
    !> Handle to the table to get the first entry of.
    integer, intent(in) :: thandle
    !> The return value signals, if there actually is such a first entry.
    logical :: exists
    if (thandle /= 0) then
      call flu_pushnil(L)
      exists = flu_next(L, thandle)
    else
      exists = .false.
    end if
  end function aot_table_first
Call graph
aot_table_first calls flu_next, flu_pushnil
flu_next calls lua_next
flu_pushnil calls lua_pushnil
aot_table_length calls aot_table_first
get_top_double_v calls aot_table_first, aot_table_length
get_top_double_vvect calls aot_table_first, aot_table_length
get_top_extdouble_v calls aot_table_first, aot_table_length
get_top_extdouble_vvect calls aot_table_first, aot_table_length
get_top_integer_v calls aot_table_first, aot_table_length
get_top_integer_vvect calls aot_table_first, aot_table_length
get_top_logical_v calls aot_table_first, aot_table_length
get_top_logical_vvect calls aot_table_first, aot_table_length
get_top_long_v calls aot_table_first, aot_table_length
get_top_long_vvect calls aot_table_first, aot_table_length
get_top_quadruple_v calls aot_table_first, aot_table_length
get_top_quadruple_vvect calls aot_table_first, aot_table_length
get_top_real_v calls aot_table_first, aot_table_length
get_top_real_vvect calls aot_table_first, aot_table_length
get_top_string_v calls aot_table_first, aot_table_length
get_top_string_vvect calls aot_table_first, aot_table_length
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_extdouble_vvect, get_top_extdouble_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v