aot_out_open_table – Aotus
aot_out_open_table Subroutine
13 statements
Source File
public subroutine aot_out_open_table(put_conf, tname, advance_previous)
Start a new table to write to.
You can give the table a name with the tname argument. If the table definition should NOT start on a new line, you have to pass in an advance_previous = .false.
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
character(len=*), intent(in), optional :: tname
logical, intent(in), optional :: advance_previous
Calls
Called by
Source Code
  subroutine aot_out_open_table(put_conf, tname, advance_previous)
    !------------------------------------------------------------------------
    type(aot_out_type), intent(inout)  :: put_conf
    character(len=*), optional, intent(in) :: tname
    logical, optional, intent(in) :: advance_previous
    !------------------------------------------------------------------------
    call aot_out_breakline(put_conf, advance_previous)
    if (present(tname)) then
      write(put_conf%outunit, fmt='(a)', advance='no') trim(tname)//' = {'
    else
      write(put_conf%outunit, fmt='(a)', advance='no') '{'
    end if
    put_conf%level = put_conf%level + 1
    put_conf%indent = put_conf%indent + put_conf%in_step
  end subroutine aot_out_open_table
Call graph
aot_out_open_table calls aot_out_breakline
aot_out_val_arr_double calls aot_out_open_table, aot_out_val
aot_out_val_arr_extdouble calls aot_out_open_table, aot_out_val
aot_out_val_arr_int calls aot_out_open_table, aot_out_val
aot_out_val_arr_logical calls aot_out_open_table, aot_out_val
aot_out_val_arr_long calls aot_out_open_table, aot_out_val
aot_out_val_arr_quadruple calls aot_out_open_table, aot_out_val
aot_out_val_arr_real calls aot_out_open_table, aot_out_val
aot_out_val_arr_string calls aot_out_open_table, aot_out_val
aot_out_val calls aot_out_val_arr_quadruple, aot_out_val_arr_extdouble, aot_out_val_arr_double, aot_out_val_arr_int, aot_out_val_arr_logical, aot_out_val_arr_long, aot_out_val_arr_real, aot_out_val_arr_string