aot_out_val_quadruple – Aotus
aot_out_val_quadruple Subroutine
18 statements
Source File
private subroutine aot_out_val_quadruple(put_conf, val, vname, advance_previous)
Put quadruple variables into the Lua script.
The value is passed in with val, optionally you can assign a name to it with the vname argument. If it should be put on the same line as the previous entry, you have to set advance_previous=.false.
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
real(kind=quad_k), intent(in) :: val
character(len=*), intent(in), optional :: vname
logical, intent(in), optional :: advance_previous
Calls
Called by
Source Code
  subroutine aot_out_val_quadruple(put_conf, val, vname, advance_previous)
    !------------------------------------------------------------------------
    type(aot_out_type), intent(inout)  :: put_conf
    character(len=*), optional, intent(in) :: vname
    logical, optional, intent(in) :: advance_previous
    real(kind=quad_k), intent(in) :: val
    !------------------------------------------------------------------------
    character(len=3) :: adv_string
    !------------------------------------------------------------------------
    if (put_conf%level > 0) then
      ! Leave the advancing to the next entry in the table.
      adv_string = 'no'
    else
      ! Not within a table, finalize the global definition with a newline.
      adv_string = 'yes'
    end if
    call aot_out_breakline(put_conf, advance_previous)
    if (present(vname)) then
      write(put_conf%outunit, fmt="(a,EN42.33)", advance=adv_string) &
        & trim(vname)//" = ", val
    else
      write(put_conf%outunit, fmt="(EN42.33)", advance=adv_string) val
    end if
  end subroutine aot_out_val_quadruple
Call graph
aot_out_val_quadruple calls aot_out_breakline
aot_out_val calls aot_out_val_quadruple, aot_out_val_arr_quadruple
aot_out_val_arr_quadruple calls aot_out_val