aot_path_open_fun – Aotus
aot_path_open_fun Subroutine
20 statements
Source File
private subroutine aot_path_open_fun(me, conf, fun, openLua)
This subroutine opens all the tables on the way to the final head node, which ought to be a function.
The given fun object is then filled by an aot_fun_open on the head of the given path. The handle can be either passed in, to be used for the look up of the path, or, when specifying the optional openLua argument as true, it will return the handle to the newly opened Lua script.
Arguments
Type Intent Optional Attributes Name
type(aot_path_type), intent(inout) :: me
The path object to open as a function
type(flu_State) :: conf
The flu_state handle, which is either opened according to the path, or used to open the path in.
type(aot_fun_type), intent(out) :: fun
The opened function
logical, intent(in), optional :: openLua
A flag to indicate, wether to open the Lua script, default is false, in which case the conf argument has to link to an actual Lua state handle.
Calls
Called by
Source Code
  subroutine aot_path_open_fun(me, conf, fun, openLua)
    !> The path object to open as a function
    type(aot_path_type), intent(inout) :: me
    !> The flu_state handle, which is either opened according to
    !! the path, or used to open the path in.
    type(flu_state) :: conf
    !> The opened function
    type(aot_fun_type), intent(out) :: fun
    !> A flag to indicate, wether to open the Lua script, default
    !! is false, in which case the conf argument has to link to
    !! an actual Lua state handle.
    logical, intent(in), optional :: openLua
    integer :: myHandle = 0
    ! open the table until it reaches the final head node
    call aot_path_open_table( me, conf, myHandle, openLua )
    if (me%head%NodeType == 'function') then
      select case(me%head%ID_kind)
      case('key')
        if (associated(me%head, me%GlobalNode)) then
          call aot_fun_open(L=conf, fun=fun, key=me%head%key)
        else
          call aot_fun_open(L=conf, parent=myHandle, fun=fun, key=me%head%key)
        end if
      case('position')
        call aot_fun_open(L=conf, parent=myHandle, fun=fun, pos=me%head%pos)
      end select
    end if
  end subroutine aot_path_open_fun
Call graph
aot_path_open_fun calls aot_fun_open, aot_path_open_table
aot_fun_open calls aot_fun_ref, aot_fun_table
aot_path_open_table calls aot_table_open, open_config_file
aot_fun_ref calls aot_fun_top, aot_reference_to_top
aot_fun_table calls aot_fun_top, aot_table_push
aot_table_open calls aot_table_push, aot_table_top, flu_createtable, flu_getglobal, flu_gettop
open_config_file calls flu_dump, aot_err_handler, flu_isopen, flu_pcall, flul_loadfile, flul_newstate, flul_openlibs
flu_dump calls flu_dump_tobuf
aot_err_handler calls flu_tolstring
aot_fun_top calls flu_gettop, flu_isfunction, flu_pushvalue, flu_topointer
aot_reference_to_top calls flu_rawgeti
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
aot_table_top calls flu_gettop, flu_istable, flu_pop
flu_createtable calls lua_createtable
flu_getglobal calls lua_getglobal
flu_gettop calls lua_gettop
flu_pcall calls lua_pcallk
flul_loadfile calls lual_loadfilex
flul_newstate calls lual_newstate
flul_openlibs calls lual_openlibs
flu_pushinteger calls flu_pushint, flu_pushlong
flu_dump_tobuf calls dump_lua_tobuf
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_isfunction calls lua_type
flu_istable calls lua_type
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_pushvalue calls lua_pushvalue
flu_rawgeti calls lua_rawgeti
flu_tolstring calls lua_tolstring
flu_topointer calls lua_topointer
flu_type calls lua_type
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
aot_path_open calls aot_path_open_fun