aot_fun_ref – Aotus
aot_fun_ref Subroutine
7 statements
Source File
private subroutine aot_fun_ref(L, fun, ref)
Get a function from a previously defned Lua reference.
Use a previously (with aot_reference_for) defined reference to get a function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
type(aot_fun_type), intent(out) :: fun
Returned handle, providing access to the function.
integer, intent(in) :: ref
Lua reference to the function.
Calls
Called by
Source Code
  subroutine aot_fun_ref(L, fun, ref)
    type(flu_state) :: L !! Handle for the Lua script.
    !> Returned handle, providing access to the function.
    type(aot_fun_type), intent(out) :: fun
    !> Lua reference to the function.
    integer, intent(in) :: ref
    call aot_reference_to_top(L, ref)
    fun = aot_fun_top(L)
  end subroutine aot_fun_ref
Call graph
aot_fun_ref calls aot_fun_top, aot_reference_to_top
aot_fun_top calls flu_gettop, flu_isfunction, flu_pushvalue, flu_topointer
aot_reference_to_top calls flu_rawgeti
flu_gettop calls lua_gettop
flu_isfunction calls lua_type
flu_pushvalue calls lua_pushvalue
flu_rawgeti calls lua_rawgeti
flu_topointer calls lua_topointer
aot_fun_open calls aot_fun_ref
aot_path_open_fun calls aot_fun_open
aot_path_open calls aot_path_open_fun