aot_fun_put_extdouble_v – Aotus
aot_fun_put_extdouble_v Subroutine
17 statements
Source File
private subroutine aot_fun_put_extdouble_v(L, fun, arg)
Put an array of extended doubles into the list of arguments for the function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
type(aot_fun_type) :: fun
Handle of the function, this argument should be put into.
real(kind=xdble_k), intent(in) :: arg(:)
Actual argument to hand over to the Lua function.
Calls
Called by
Source Code
  subroutine aot_fun_put_extdouble_v(L, fun, arg)
    type(flu_state) :: L !< Handle for the Lua script.
    !> Handle of the function, this argument should be put into.
    type(aot_fun_type) :: fun
    !> Actual argument to hand over to the Lua function.
    real(kind=xdble_k), intent(in) :: arg(:)
    real(kind=double_k) :: locarg(size(arg))
    integer :: thandle
    ! Only do something, if the function is actually properly defined.
    if (fun%handle /= 0) then
      locarg = real(arg, kind=double_k)
      ! If the function was executed before this call, it has to be
      ! reset.
      if (fun%arg_count == -1) then
        ! Set the top of the stack to the reference of the function.
        ! Discarding anything above it.
        call flu_settop(L, fun%handle)
        ! Push a copy of the function itself on the stack again, before
        ! adding arguments, to savely survive popping of the function
        ! upon execution.
        call flu_pushvalue(L, fun%handle)
        ! Increase the argument count to 0 again (really start counting
        ! arguments afterwards.
        fun%arg_count = fun%arg_count+1
      end if
      call aot_table_from_1Darray(L, thandle, locarg)
      fun%arg_count = fun%arg_count+1
    end if
  end subroutine aot_fun_put_extdouble_v
Call graph
aot_fun_put_extdouble_v calls aot_table_from_1darray, flu_pushvalue, flu_settop
aot_table_from_1darray calls create_1darray_extdouble
flu_pushvalue calls lua_pushvalue
flu_settop calls lua_settop
create_1darray_extdouble calls flu_pushinteger, flu_pushnumber, flu_createtable, flu_gettop, flu_settable
flu_pushinteger calls flu_pushint, flu_pushlong
flu_pushnumber calls flu_pushdouble, flu_pushreal
flu_createtable calls lua_createtable
flu_gettop calls lua_gettop
flu_settable calls lua_settable
flu_pushdouble calls lua_pushnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_pushreal calls lua_pushnumber
aot_fun_put calls aot_fun_put_extdouble_v