aot_table_close – Aotus
aot_table_close Subroutine
5 statements
Source File
public subroutine aot_table_close(L, thandle)
Close a table again.
This is done by popping all values above and itself from the stack.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
integer, intent(in) :: thandle
Handle of the table to close.
Calls
Called by
Source Code
  subroutine aot_table_close(L, thandle)
    type(flu_state) :: L !! Handle for the Lua script.
    !> Handle of the table to close.
    integer, intent(in) :: thandle
    if (thandle > 0) call flu_settop(L, thandle-1)
  end subroutine aot_table_close
Call graph
aot_table_close calls flu_settop
flu_settop calls lua_settop
aot_path_close_table calls aot_table_close
aot_require_buffer calls aot_table_close
get_top_double_v calls aot_table_close
get_top_double_vvect calls aot_table_close
get_top_extdouble_v calls aot_table_close
get_top_extdouble_vvect calls aot_table_close
get_top_integer_v calls aot_table_close
get_top_integer_vvect calls aot_table_close
get_top_logical_v calls aot_table_close
get_top_logical_vvect calls aot_table_close
get_top_long_v calls aot_table_close
get_top_long_vvect calls aot_table_close
get_top_quadruple_v calls aot_table_close
get_top_quadruple_vvect calls aot_table_close
get_top_real_v calls aot_table_close
get_top_real_vvect calls aot_table_close
get_top_string_v calls aot_table_close
get_top_string_vvect calls aot_table_close
aot_path_close calls aot_path_close_table, aot_path_close_fun
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_extdouble_vvect, get_top_extdouble_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v
aot_path_close_fun calls aot_path_close_table