aot_out_val_extdouble – Aotus
aot_out_val_extdouble Subroutine
18 statements
Source File
private subroutine aot_out_val_extdouble(put_conf, val, vname, advance_previous)
Put extdouble variables into the Lua script.
The value is passed in with val, optionally you can assign a name to it with the vname argument. If it should be put on the same line as the previous entry, you have to set advance_previous=.false.
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
real(kind=xdble_k), intent(in) :: val
character(len=*), intent(in), optional :: vname
logical, intent(in), optional :: advance_previous
Calls
Called by
Source Code
  subroutine aot_out_val_extdouble(put_conf, val, vname, advance_previous)
    !------------------------------------------------------------------------
    type(aot_out_type), intent(inout)  :: put_conf
    character(len=*), optional, intent(in) :: vname
    logical, optional, intent(in) :: advance_previous
    real(kind=xdble_k), intent(in) :: val
    !------------------------------------------------------------------------
    character(len=3) :: adv_string
    !------------------------------------------------------------------------
    if (put_conf%level > 0) then
      ! Leave the advancing to the next entry in the table.
      adv_string = 'no'
    else
      ! Not within a table, finalize the global definition with a newline.
      adv_string = 'yes'
    end if
    call aot_out_breakline(put_conf, advance_previous)
    if (present(vname)) then
      write(put_conf%outunit, fmt="(a,EN24.15)", advance=adv_string) &
        & trim(vname)//" = ", val
    else
      write(put_conf%outunit, fmt="(EN24.15)", advance=adv_string) val
    end if
  end subroutine aot_out_val_extdouble
Call graph
aot_out_val_extdouble calls aot_out_breakline
aot_out_val calls aot_out_val_extdouble, aot_out_val_arr_extdouble, aot_out_val_arr_double, aot_out_val_arr_int, aot_out_val_arr_logical, aot_out_val_arr_long, aot_out_val_arr_real, aot_out_val_arr_string
aot_out_val_arr_double calls aot_out_val
aot_out_val_arr_extdouble calls aot_out_val
aot_out_val_arr_int calls aot_out_val
aot_out_val_arr_logical calls aot_out_val
aot_out_val_arr_long calls aot_out_val
aot_out_val_arr_real calls aot_out_val
aot_out_val_arr_string calls aot_out_val