aot_fun_close – Aotus
aot_fun_close Subroutine
8 statements
Source File
public subroutine aot_fun_close(L, fun)
Close the function again (pop everything above from the stack).
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
type(aot_fun_type) :: fun
Handle to the function to close.
Calls
Called by
Source Code
  subroutine aot_fun_close(L, fun)
    type(flu_state) :: L !! Handle for the Lua script.
    !> Handle to the function to close.
    type(aot_fun_type) :: fun
    if (fun%handle > 0) call flu_settop(L, fun%handle-1)
    fun%handle = 0
    fun%id = 0
    fun%arg_count = 0
  end subroutine aot_fun_close
Call graph
aot_fun_close calls flu_settop
flu_settop calls lua_settop
aot_path_close_fun calls aot_fun_close
aot_path_close calls aot_path_close_fun