create_1Darray_extdouble – Aotus
create_1Darray_extdouble Subroutine
21 statements
Source File
private subroutine create_1Darray_extdouble(L, thandle, val)
This subroutine takes a one dimensional array, and puts it as a table into the Lua context.
The returned thandle provides the index to access this newly created table.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer, intent(out) :: thandle
Handle to access the newly created table.
real(kind=xdble_k), intent(in) :: val(:)
Values to put into the new table.
Calls
Called by
Source Code
  subroutine create_1Darray_extdouble(L, thandle, val)
    type(flu_State) :: L !< Handle to the Lua script.
    !> Handle to access the newly created table.
    integer, intent(out) :: thandle
    !> Values to put into the new table.
    real(kind=xdble_k), intent(in) :: val(:)
    integer :: tab
    integer :: nvals
    integer :: i
    real(kind=double_k), allocatable :: locval(:)
    nVals = size(val)
    allocate(locVal(nVals))
    locVal(:) = real(val, kind=double_k)
    call flu_createtable(L, nVals, 0)
    thandle = flu_gettop(L)
    tab = thandle
    do i=1,nVals
      call flu_pushInteger(L, i)
      call flu_pushNumber(L, locval(i))
      call flu_settable(L, tab)
    end do
    deallocate(locval)
  end subroutine create_1Darray_extdouble
Call graph
create_1darray_extdouble calls flu_pushinteger, flu_pushnumber, flu_createtable, flu_gettop, flu_settable
flu_pushinteger calls flu_pushint, flu_pushlong
flu_pushnumber calls flu_pushdouble, flu_pushreal
flu_createtable calls lua_createtable
flu_gettop calls lua_gettop
flu_settable calls lua_settable
flu_pushdouble calls lua_pushnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_pushreal calls lua_pushnumber
aot_table_from_1darray calls create_1darray_extdouble
aot_fun_put_double_v calls aot_table_from_1darray
aot_fun_put_extdouble_v calls aot_table_from_1darray
aot_fun_put_quadruple_v calls aot_table_from_1darray
aot_fun_put_single_v calls aot_table_from_1darray
aot_fun_put calls aot_fun_put_double_v, aot_fun_put_single_v, aot_fun_put_extdouble_v, aot_fun_put_quadruple_v