flu_dump_toBuf – Aotus
flu_dump_toBuf Subroutine
18 statements
Source File
private subroutine flu_dump_toBuf(L, buf, length, iError)
Dump to a buffer and return the pointer to the resulting string.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
type(cbuf_type), intent(out) :: buf
integer :: length
integer :: iError
Calls
Called by
Source Code
  subroutine flu_dump_toBuf(L, buf, length, iError)
    type(flu_State) :: L
    type(cbuf_type), intent(out) :: buf
    integer :: length
    integer :: iError
    type(c_ptr) :: string_c
    integer(kind=c_int) :: length_c
    integer(kind=c_int) :: iErr
    string_c = dump_lua_toBuf(L%state, length_c, iErr)
    iError = int(iErr)
    if (iError == 0) then
      length = int(length_c)
      buf%ptr = string_c
      call c_f_pointer(string_c, buf%buffer, [length])
    else
      length = 0
    end if
  end subroutine flu_dump_toBuf
Call graph
flu_dump_tobuf calls dump_lua_tobuf
flu_dump calls flu_dump_tobuf
aot_file_to_buffer calls flu_dump
open_config_file calls flu_dump
aot_path_open_table calls open_config_file
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table