flu_isopen – Aotus
flu_isopen Function
5 statements
Source File
public function flu_isopen(L) result(is_open)
Arguments
Type Intent Optional Attributes Name
type(flu_State), intent(in) :: L
Return Value logical
Called by
Source Code
  function flu_isopen(L) result(is_open)
      logical :: is_open
      type(flu_State), intent(in) :: L
      is_open = c_associated(L%state)
  end function flu_isopen
Call graph
open_config_buffer calls flu_isopen
open_config_chunk calls flu_isopen
open_config_file calls flu_isopen
aot_path_open_table calls open_config_file
aot_require_buffer calls open_config_buffer
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table