flu_insert – Aotus
flu_insert Subroutine
7 statements
Source File
public subroutine flu_insert(L, index)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer :: index
Calls
Called by
Source Code
  subroutine flu_insert(L, index)
    type(flu_state) :: L
    integer :: index
    integer(kind=c_int) :: c_index
    c_index = int(index, kind = c_int)
    call lua_rotate(L%state, c_index, 1_c_int)
  end subroutine flu_insert
Call graph
flu_insert calls lua_rotate
aot_fun_put_top calls flu_insert
aot_table_set_top calls flu_insert
aot_fun_put calls aot_fun_put_top