flu_pushvalue – Aotus
flu_pushvalue Subroutine
7 statements
Source File
public subroutine flu_pushvalue(L, index)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer :: index
Calls
Called by
Source Code
  subroutine flu_pushvalue(L, index)
    type(flu_State) :: L
    integer :: index
    integer(kind=c_int) :: c_index
    c_index = index
    call lua_pushvalue(L%state, c_index)
  end subroutine flu_pushvalue
Call graph
flu_pushvalue calls lua_pushvalue
aot_fun_put_double calls flu_pushvalue
aot_fun_put_double_v calls flu_pushvalue
aot_fun_put_extdouble calls flu_pushvalue
aot_fun_put_extdouble_v calls flu_pushvalue
aot_fun_put_quadruple calls flu_pushvalue
aot_fun_put_quadruple_v calls flu_pushvalue
aot_fun_put_single calls flu_pushvalue
aot_fun_put_single_v calls flu_pushvalue
aot_fun_top calls flu_pushvalue
aot_fun_put calls aot_fun_put_quadruple, aot_fun_put_quadruple_v, aot_fun_put_extdouble, aot_fun_put_extdouble_v, aot_fun_put_double, aot_fun_put_double_v, aot_fun_put_single, aot_fun_put_single_v
aot_fun_ref calls aot_fun_top
aot_fun_table calls aot_fun_top
aot_fun_open calls aot_fun_ref, aot_fun_table
aot_path_open_fun calls aot_fun_open
aot_path_open calls aot_path_open_fun