flu_pushreal – Aotus
flu_pushreal Subroutine
7 statements
Source File
private subroutine flu_pushreal(L, n)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
real :: n
Calls
Called by
Source Code
  subroutine flu_pushreal(L, n)
    type(flu_State) :: L
    real :: n
    real(kind=c_double) :: n_c
    n_c = real(n, c_double)
    call lua_pushnumber(L%state, n_c)
  end subroutine flu_pushreal
Call graph
flu_pushreal calls lua_pushnumber
flu_pushnumber calls flu_pushreal
aot_fun_put_double calls flu_pushnumber
aot_fun_put_extdouble calls flu_pushnumber
aot_fun_put_quadruple calls flu_pushnumber
aot_fun_put_single calls flu_pushnumber
create_1darray_double calls flu_pushnumber
create_1darray_extdouble calls flu_pushnumber
create_1darray_quadruple calls flu_pushnumber
create_1darray_real calls flu_pushnumber
set_table_double calls flu_pushnumber
set_table_extdouble calls flu_pushnumber
set_table_quadruple calls flu_pushnumber
set_table_real calls flu_pushnumber
aot_fun_put calls aot_fun_put_double, aot_fun_put_single, aot_fun_put_double_v, aot_fun_put_single_v, aot_fun_put_quadruple, aot_fun_put_quadruple_v, aot_fun_put_extdouble, aot_fun_put_extdouble_v
aot_table_from_1darray calls create_1darray_extdouble, create_1darray_double, create_1darray_real, create_1darray_quadruple
aot_table_set_val calls set_table_extdouble, set_table_double, set_table_real, set_table_quadruple
aot_fun_put_double_v calls aot_table_from_1darray
aot_fun_put_extdouble_v calls aot_table_from_1darray
aot_fun_put_quadruple_v calls aot_table_from_1darray
aot_fun_put_single_v calls aot_table_from_1darray
aot_require_buffer calls aot_table_set_val