flu_close – Aotus
flu_close Subroutine
5 statements
Source File
public subroutine flu_close(L)
Close a previously opened Lua script.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle to the Lua state to close.
Calls
Called by
Source Code
  subroutine flu_close(L)
    type(flu_State) :: L !! Handle to the Lua state to close.
    call lua_close(L%state)
    L%state = c_null_ptr
  end subroutine flu_close
Call graph
flu_close calls lua_close
close_config calls flu_close
test calls flu_close
aot_file_to_buffer calls close_config
aot_path_close_table calls close_config
aot_path_close calls aot_path_close_table, aot_path_close_fun
aot_path_close_fun calls aot_path_close_table