flu_register – Aotus
flu_register Subroutine
7 statements
Source File
public subroutine flu_register(L, fn_name, fn)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
character(len=*), intent(in) :: fn_name
procedure(lua_Function) :: fn
Calls
Source Code
  subroutine flu_register(L, fn_name, fn)
    ! lua_register is defined as a macro in lua.h and isn't accessible from
    ! Fortran.
    ! Re-implement macro explicitly.
    type(flu_State) :: L
    character(len=*), intent(in) :: fn_name
    procedure(lua_Function) :: fn
    call flu_pushcclosure(L, fn, 0)
    call flu_setglobal(L, fn_name)
  end subroutine flu_register
Call graph
flu_register calls flu_pushcclosure, flu_setglobal
flu_pushcclosure calls lua_pushcclosure
flu_setglobal calls lua_setglobal