flu_settable – Aotus
flu_settable Subroutine
7 statements
Source File
public subroutine flu_settable(L, n)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer, intent(in) :: n
Calls
Called by
Source Code
  subroutine flu_settable(L, n)
    type(flu_State) :: L
    integer, intent(in) :: n
    integer(kind=c_int) :: n_c
    n_c = n
    call lua_settable(L%state, n_c)
  end subroutine flu_settable
Call graph
flu_settable calls lua_settable
aot_table_set_top calls flu_settable
create_1darray_double calls flu_settable
create_1darray_extdouble calls flu_settable
create_1darray_quadruple calls flu_settable
create_1darray_real calls flu_settable
set_table_double calls flu_settable
set_table_extdouble calls flu_settable
set_table_integer calls flu_settable
set_table_logical calls flu_settable
set_table_long calls flu_settable
set_table_quadruple calls flu_settable
set_table_real calls flu_settable
set_table_string calls flu_settable
set_table_userdata calls flu_settable
aot_table_from_1darray calls create_1darray_double, create_1darray_real, create_1darray_quadruple, create_1darray_extdouble
aot_table_set_val calls set_table_double, set_table_integer, set_table_logical, set_table_long, set_table_real, set_table_string, set_table_userdata, set_table_quadruple, set_table_extdouble
aot_fun_put_double_v calls aot_table_from_1darray
aot_fun_put_extdouble_v calls aot_table_from_1darray
aot_fun_put_quadruple_v calls aot_table_from_1darray
aot_fun_put_single_v calls aot_table_from_1darray
aot_require_buffer calls aot_table_set_val
aot_fun_put calls aot_fun_put_quadruple_v, aot_fun_put_extdouble_v, aot_fun_put_double_v, aot_fun_put_single_v