flu_topointer – Aotus
flu_topointer Function
10 statements
Source File
public function flu_topointer(L, index) result(intptr)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer :: index
Return Value integer(kind=long_k)
Calls
Called by
Source Code
  function flu_topointer(L, index) result(intptr)
    type(flu_State) :: L
    integer :: index
    integer(kind=long_k) :: intptr
    integer(kind=c_intptr_t) :: ptr
    integer(kind=c_int) :: c_index
    c_index = index
    ptr = lua_topointer(L%state, c_index)
    intptr = int(ptr, kind=long_k)
  end function flu_topointer
Call graph
flu_topointer calls lua_topointer
aot_fun_top calls flu_topointer
aot_fun_ref calls aot_fun_top
aot_fun_table calls aot_fun_top
aot_fun_open calls aot_fun_ref, aot_fun_table
aot_path_open_fun calls aot_fun_open
aot_path_open calls aot_path_open_fun