flu_getglobal – Aotus
flu_getglobal Function
10 statements
Source File
public function flu_getglobal(L, k) result(luatype)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
character(len=*) :: k
Return Value integer
Calls
Called by
Source Code
  function flu_getglobal(L, k) result(luatype)
    type(flu_State)  :: L
    character(len=*) :: k
    integer          :: luatype
    integer(kind=c_int) :: res
    character(len=len_trim(k)+1) :: c_k
    c_k = trim(k) // c_null_char
    res = lua_getglobal(L%state, c_k)
    luatype = int(res)
  end function flu_getglobal
Call graph
flu_getglobal calls lua_getglobal
aot_reference_for calls flu_getglobal, aot_table_push
aot_table_open calls flu_getglobal, aot_table_push
aot_table_push calls flu_getglobal
aot_type_of calls flu_getglobal, aot_table_push
get_table_double calls flu_getglobal, aot_table_push
get_table_extdouble calls flu_getglobal, aot_table_push
get_table_extdouble_v calls flu_getglobal, aot_table_push
get_table_extdouble_vvect calls flu_getglobal, aot_table_push
get_table_integer calls flu_getglobal, aot_table_push
get_table_logical calls flu_getglobal, aot_table_push
get_table_long calls flu_getglobal, aot_table_push
get_table_quadruple calls flu_getglobal, aot_table_push
get_table_quadruple_v calls flu_getglobal, aot_table_push
get_table_quadruple_vvect calls flu_getglobal, aot_table_push
get_table_real calls flu_getglobal, aot_table_push
get_table_string calls flu_getglobal, aot_table_push
get_table_userdata calls flu_getglobal, aot_table_push
test calls flu_getglobal
aot_get_val calls get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_quadruple_vvect, get_table_quadruple_v, get_table_quadruple, get_table_extdouble_vvect, get_table_extdouble_v, get_table_extdouble, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_push calls aot_table_push
aot_table_get_val calls get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_quadruple_vvect, get_table_quadruple_v, get_table_quadruple, get_table_extdouble_vvect, get_table_extdouble_v, get_table_extdouble, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_exists calls aot_table_push
aot_fun_table calls aot_table_push
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
get_table_double_v calls aot_type_of
get_table_double_vvect calls aot_type_of
get_table_integer_v calls aot_type_of
get_table_integer_vvect calls aot_type_of
get_table_logical_v calls aot_type_of
get_table_logical_vvect calls aot_type_of
get_table_long_v calls aot_type_of
get_table_long_vvect calls aot_type_of
get_table_real_v calls aot_type_of
get_table_real_vvect calls aot_type_of
get_table_string_v calls aot_type_of
get_table_string_vvect calls aot_type_of
aot_fun_open calls aot_fun_table
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table, aot_fun_open