flu_pcall – Aotus
flu_pcall Function
16 statements
Source File
public function flu_pcall(L, nargs, nresults, errfunc) result(errcode)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer :: nargs
integer :: nresults
integer :: errfunc
Return Value integer
Calls
Called by
Source Code
  function flu_pcall(L, nargs, nresults, errfunc) result(errcode)
    type(flu_State) :: L
    integer :: nargs
    integer :: nresults
    integer :: errfunc
    integer :: errcode
    integer(kind=c_int) :: c_nargs
    integer(kind=c_int) :: c_nresults
    integer(kind=c_int) :: c_errfunc
    integer(kind=c_int) :: c_errcode
    c_nargs = nargs
    c_nresults = nresults
    c_errfunc = errfunc
    c_errcode = lua_pcallk(L%state, c_nargs, c_nresults, c_errfunc, &
      &                    0_c_int, C_NULL_PTR)
    errcode = c_errcode
  end function flu_pcall
Call graph
flu_pcall calls lua_pcallk
aot_fun_do calls flu_pcall
open_config_buffer calls flu_pcall
open_config_chunk calls flu_pcall
open_config_file calls flu_pcall
test calls flu_pcall
aot_path_open_table calls open_config_file
aot_require_buffer calls open_config_buffer
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table