flu_pop – Aotus
flu_pop Subroutine
8 statements
Source File
public subroutine flu_pop(L, n)
Wrapper for lua_pop that pops n elements from the Lua API stack.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle to the Lua script
integer, intent(in), optional :: n
Number of elements to pop from the Lua API stack, defaults to 1.
Calls
Called by
Source Code
  subroutine flu_pop(L, n)
    type(flu_State) :: L !! Handle to the Lua script
    !> Number of elements to pop from the Lua API stack, defaults to 1.
    integer, optional, intent(in) :: n
    integer(kind=c_int) :: n_c
    n_c = -2
    if (present(n)) n_c = -n-1
    call lua_settop(L%state, n_c)
  end subroutine flu_pop
Call graph
flu_pop calls lua_settop
aot_exists calls flu_pop, aot_table_push
aot_table_length calls flu_pop
aot_table_push calls flu_pop
aot_table_top calls flu_pop
aot_top_get_double calls flu_pop
aot_top_get_extdouble calls flu_pop
aot_top_get_integer calls flu_pop
aot_top_get_logical calls flu_pop
aot_top_get_long calls flu_pop
aot_top_get_quadruple calls flu_pop
aot_top_get_real calls flu_pop
aot_top_get_string calls flu_pop
aot_top_get_userdata calls flu_pop
aot_push calls aot_table_push
aot_top_get_val calls aot_top_get_quadruple, aot_top_get_double, aot_top_get_integer, aot_top_get_logical, aot_top_get_long, aot_top_get_real, aot_top_get_string, aot_top_get_userdata, aot_top_get_extdouble, get_top_quadruple_vvect, get_top_quadruple_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v, get_top_extdouble_vvect, get_top_extdouble_v
aot_fun_table calls aot_table_push
aot_reference_for calls aot_table_push
aot_table_open calls aot_table_push, aot_table_top
aot_type_of calls aot_table_push
get_table_double calls aot_table_push, aot_top_get_val
get_table_extdouble calls aot_table_push, aot_top_get_val
get_table_extdouble_v calls aot_table_push, aot_top_get_val
get_table_extdouble_vvect calls aot_table_push, aot_top_get_val
get_table_integer calls aot_table_push, aot_top_get_val
get_table_logical calls aot_table_push, aot_top_get_val
get_table_long calls aot_table_push, aot_top_get_val
get_table_quadruple calls aot_table_push, aot_top_get_val
get_table_quadruple_v calls aot_table_push, aot_top_get_val
get_table_quadruple_vvect calls aot_table_push, aot_top_get_val
get_table_real calls aot_table_push, aot_top_get_val
get_table_string calls aot_table_push, aot_top_get_val
get_table_userdata calls aot_table_push, aot_top_get_val
get_top_double_v calls aot_table_length, aot_table_top, aot_top_get_val
get_top_double_vvect calls aot_table_length, aot_table_top, aot_top_get_val
get_top_extdouble_v calls aot_table_length, aot_table_top, aot_top_get_val
get_top_extdouble_vvect calls aot_table_length, aot_table_top, aot_top_get_val
get_top_integer_v calls aot_table_length, aot_table_top, aot_top_get_val
get_top_integer_vvect calls aot_table_length, aot_table_top, aot_top_get_val
get_top_logical_v calls aot_table_length, aot_table_top, aot_top_get_val
get_top_logical_vvect calls aot_table_length, aot_table_top, aot_top_get_val
get_top_long_v calls aot_table_length, aot_table_top, aot_top_get_val
get_top_long_vvect calls aot_table_length, aot_table_top, aot_top_get_val
get_top_quadruple_v calls aot_table_length, aot_table_top, aot_top_get_val
get_top_quadruple_vvect calls aot_table_length, aot_table_top, aot_top_get_val
get_top_real_v calls aot_table_length, aot_table_top, aot_top_get_val
get_top_real_vvect calls aot_table_length, aot_table_top, aot_top_get_val
get_top_string_v calls aot_table_length, aot_table_top, aot_top_get_val
get_top_string_vvect calls aot_table_length, aot_table_top, aot_top_get_val
aot_fun_open calls aot_fun_table
aot_get_val calls get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_quadruple_vvect, get_table_quadruple_v, get_table_quadruple, get_table_extdouble_vvect, get_table_extdouble_v, get_table_extdouble, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_table_get_val calls get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_quadruple_vvect, get_table_quadruple_v, get_table_quadruple, get_table_extdouble_vvect, get_table_extdouble_v, get_table_extdouble, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
get_table_double_v calls aot_top_get_val, aot_type_of
get_table_double_vvect calls aot_top_get_val, aot_type_of
get_table_integer_v calls aot_top_get_val, aot_type_of
get_table_integer_vvect calls aot_top_get_val, aot_type_of
get_table_logical_v calls aot_top_get_val, aot_type_of
get_table_logical_vvect calls aot_top_get_val, aot_type_of
get_table_long_v calls aot_top_get_val, aot_type_of
get_table_long_vvect calls aot_top_get_val, aot_type_of
get_table_real_v calls aot_top_get_val, aot_type_of
get_table_real_vvect calls aot_top_get_val, aot_type_of
get_table_string_v calls aot_top_get_val, aot_type_of
get_table_string_vvect calls aot_top_get_val, aot_type_of
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_fun_open, aot_path_open_table