flu_settop – Aotus
flu_settop Subroutine
7 statements
Source File
public subroutine flu_settop(L, n)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer, intent(in) :: n
Calls
Called by
Source Code
  subroutine flu_settop(L, n)
    type(flu_State) :: L
    integer, intent(in) :: n
    integer(kind=c_int) :: n_c
    n_c = n
    call lua_settop(L%state, n_c)
  end subroutine flu_settop
Call graph
flu_settop calls lua_settop
aot_fun_close calls flu_settop
aot_fun_put_double calls flu_settop
aot_fun_put_double_v calls flu_settop
aot_fun_put_extdouble calls flu_settop
aot_fun_put_extdouble_v calls flu_settop
aot_fun_put_quadruple calls flu_settop
aot_fun_put_quadruple_v calls flu_settop
aot_fun_put_single calls flu_settop
aot_fun_put_single_v calls flu_settop
aot_table_close calls flu_settop
aot_fun_put calls aot_fun_put_double, aot_fun_put_double_v, aot_fun_put_single, aot_fun_put_single_v, aot_fun_put_quadruple, aot_fun_put_quadruple_v, aot_fun_put_extdouble, aot_fun_put_extdouble_v
aot_path_close_fun calls aot_fun_close, aot_path_close_table
aot_path_close_table calls aot_table_close
aot_require_buffer calls aot_table_close
get_top_double_v calls aot_table_close
get_top_double_vvect calls aot_table_close
get_top_extdouble_v calls aot_table_close
get_top_extdouble_vvect calls aot_table_close
get_top_integer_v calls aot_table_close
get_top_integer_vvect calls aot_table_close
get_top_logical_v calls aot_table_close
get_top_logical_vvect calls aot_table_close
get_top_long_v calls aot_table_close
get_top_long_vvect calls aot_table_close
get_top_quadruple_v calls aot_table_close
get_top_quadruple_vvect calls aot_table_close
get_top_real_v calls aot_table_close
get_top_real_vvect calls aot_table_close
get_top_string_v calls aot_table_close
get_top_string_vvect calls aot_table_close
aot_path_close calls aot_path_close_fun, aot_path_close_table
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_extdouble_vvect, get_top_extdouble_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v