flu_isTable – Aotus
flu_isTable Function
8 statements
Source File
public function flu_isTable(L, index) result(is_Table)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer :: index
Return Value logical
Calls
Called by
Source Code
  function flu_isTable(L, index) result(is_Table)
    type(flu_State) :: L
    integer         :: index
    logical         :: is_Table
    integer(kind=c_int) :: c_index
    c_index = int(index, kind = c_int)
    ! Only defined as a Macro, using lua_type:
    is_Table = (lua_type(L%state, c_index) == LUA_TTABLE)
  end function flu_isTable
Call graph
flu_istable calls lua_type
aot_table_top calls flu_istable
aot_table_open calls aot_table_top
get_top_double_v calls aot_table_top
get_top_double_vvect calls aot_table_top
get_top_extdouble_v calls aot_table_top
get_top_extdouble_vvect calls aot_table_top
get_top_integer_v calls aot_table_top
get_top_integer_vvect calls aot_table_top
get_top_logical_v calls aot_table_top
get_top_logical_vvect calls aot_table_top
get_top_long_v calls aot_table_top
get_top_long_vvect calls aot_table_top
get_top_quadruple_v calls aot_table_top
get_top_quadruple_vvect calls aot_table_top
get_top_real_v calls aot_table_top
get_top_real_vvect calls aot_table_top
get_top_string_v calls aot_table_top
get_top_string_vvect calls aot_table_top
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v, get_top_extdouble_vvect, get_top_extdouble_v
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table