flu_next – Aotus
flu_next Function
10 statements
Source File
public function flu_next(L, index) result(exists)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer, intent(in) :: index
Return Value logical
Calls
Called by
Source Code
  function flu_next(L, index) result(exists)
    type(flu_State) :: L
    integer, intent(in) :: index
    logical :: exists
    integer(kind=c_int) :: retCode
    integer(kind=c_int) :: c_index
    c_index = int(index, kind = c_int)
    retCode = lua_next(L%state, c_index)
    exists = (retCode /= 0)
  end function flu_next
Call graph
flu_next calls lua_next
aot_table_first calls flu_next
aot_table_length calls flu_next, aot_table_first
get_top_double_v calls flu_next, aot_table_first, aot_table_length
get_top_double_vvect calls flu_next, aot_table_first, aot_table_length
get_top_extdouble_v calls flu_next, aot_table_first, aot_table_length
get_top_extdouble_vvect calls flu_next, aot_table_first, aot_table_length
get_top_integer_v calls flu_next, aot_table_first, aot_table_length
get_top_integer_vvect calls flu_next, aot_table_first, aot_table_length
get_top_logical_v calls flu_next, aot_table_first, aot_table_length
get_top_logical_vvect calls flu_next, aot_table_first, aot_table_length
get_top_long_v calls flu_next, aot_table_first, aot_table_length
get_top_long_vvect calls flu_next, aot_table_first, aot_table_length
get_top_quadruple_v calls flu_next, aot_table_first, aot_table_length
get_top_quadruple_vvect calls flu_next, aot_table_first, aot_table_length
get_top_real_v calls flu_next, aot_table_first, aot_table_length
get_top_real_vvect calls flu_next, aot_table_first, aot_table_length
get_top_string_v calls flu_next, aot_table_first, aot_table_length
get_top_string_vvect calls flu_next, aot_table_first, aot_table_length
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_extdouble_vvect, get_top_extdouble_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v