flu_pushnil – Aotus
flu_pushnil Subroutine
4 statements
Source File
public subroutine flu_pushnil(L)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Calls
Called by
Source Code
  subroutine flu_pushnil(L)
    type(flu_State) :: L
    call lua_pushnil(L%state)
  end subroutine flu_pushnil
Call graph
flu_pushnil calls lua_pushnil
aot_table_first calls flu_pushnil
aot_table_push calls flu_pushnil
aot_push calls aot_table_push
aot_exists calls aot_table_push
aot_fun_table calls aot_table_push
aot_reference_for calls aot_table_push
aot_table_length calls aot_table_first
aot_table_open calls aot_table_push
aot_type_of calls aot_table_push
get_table_double calls aot_table_push
get_table_extdouble calls aot_table_push
get_table_extdouble_v calls aot_table_push
get_table_extdouble_vvect calls aot_table_push
get_table_integer calls aot_table_push
get_table_logical calls aot_table_push
get_table_long calls aot_table_push
get_table_quadruple calls aot_table_push
get_table_quadruple_v calls aot_table_push
get_table_quadruple_vvect calls aot_table_push
get_table_real calls aot_table_push
get_table_string calls aot_table_push
get_table_userdata calls aot_table_push
get_top_double_v calls aot_table_first, aot_table_length
get_top_double_vvect calls aot_table_first, aot_table_length
get_top_extdouble_v calls aot_table_first, aot_table_length
get_top_extdouble_vvect calls aot_table_first, aot_table_length
get_top_integer_v calls aot_table_first, aot_table_length
get_top_integer_vvect calls aot_table_first, aot_table_length
get_top_logical_v calls aot_table_first, aot_table_length
get_top_logical_vvect calls aot_table_first, aot_table_length
get_top_long_v calls aot_table_first, aot_table_length
get_top_long_vvect calls aot_table_first, aot_table_length
get_top_quadruple_v calls aot_table_first, aot_table_length
get_top_quadruple_vvect calls aot_table_first, aot_table_length
get_top_real_v calls aot_table_first, aot_table_length
get_top_real_vvect calls aot_table_first, aot_table_length
get_top_string_v calls aot_table_first, aot_table_length
get_top_string_vvect calls aot_table_first, aot_table_length
aot_fun_open calls aot_fun_table
aot_get_val calls get_table_quadruple_vvect, get_table_quadruple_v, get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_extdouble_vvect, get_table_extdouble_v, get_table_quadruple, get_table_extdouble, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_table_get_val calls get_table_quadruple_vvect, get_table_quadruple_v, get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_extdouble_vvect, get_table_extdouble_v, get_table_quadruple, get_table_extdouble, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_extdouble_vvect, get_top_extdouble_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
get_table_double_v calls aot_type_of
get_table_double_vvect calls aot_type_of
get_table_integer_v calls aot_type_of
get_table_integer_vvect calls aot_type_of
get_table_logical_v calls aot_type_of
get_table_logical_vvect calls aot_type_of
get_table_long_v calls aot_type_of
get_table_long_vvect calls aot_type_of
get_table_real_v calls aot_type_of
get_table_real_vvect calls aot_type_of
get_table_string_v calls aot_type_of
get_table_string_vvect calls aot_type_of
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_fun_open, aot_path_open_table