flu_touserdata – Aotus
flu_touserdata Function
8 statements
Source File
public function flu_touserdata(L, index) result(ptr)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer :: index
Return Value type(c_ptr)
Calls
Called by
Source Code
  function flu_touserdata(L, index) result(ptr)
    type(flu_State) :: L
    integer :: index
    type(c_ptr) :: ptr
    integer(kind=c_int) :: c_index
    c_index = index
    ptr = lua_touserdata(L%state, c_index)
  end function flu_touserdata
Call graph
flu_touserdata calls lua_touserdata
aot_top_get_userdata calls flu_touserdata
aot_top_get_val calls aot_top_get_userdata