flu_isNoneOrNil – Aotus
flu_isNoneOrNil Function
8 statements
Source File
public function flu_isNoneOrNil(L, index) result(is_NoneOrNil)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer :: index
Return Value logical
Calls
Called by
Source Code
  function flu_isNoneOrNil(L, index) result(is_NoneOrNil)
    type(flu_State) :: L
    integer         :: index
    logical         :: is_NoneOrNil
    integer(kind=c_int) :: c_index
    c_index = int(index, kind = c_int)
    ! Only defined as a Macro, using lua_type:
    is_NoneOrNil = (lua_Type(L%state, c_index) <= 0)
  end function flu_isNoneOrNil
Call graph
flu_isnoneornil calls lua_type
aot_top_get_double calls flu_isnoneornil
aot_top_get_extdouble calls flu_isnoneornil
aot_top_get_integer calls flu_isnoneornil
aot_top_get_logical calls flu_isnoneornil
aot_top_get_long calls flu_isnoneornil
aot_top_get_quadruple calls flu_isnoneornil
aot_top_get_real calls flu_isnoneornil
aot_top_get_string calls flu_isnoneornil
aot_top_get_userdata calls flu_isnoneornil
aot_top_get_val calls aot_top_get_quadruple, aot_top_get_extdouble, aot_top_get_double, aot_top_get_integer, aot_top_get_logical, aot_top_get_long, aot_top_get_real, aot_top_get_string, aot_top_get_userdata, get_top_quadruple_vvect, get_top_quadruple_v, get_top_extdouble_vvect, get_top_extdouble_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v
get_table_double calls aot_top_get_val
get_table_double_v calls aot_top_get_val
get_table_double_vvect calls aot_top_get_val
get_table_extdouble calls aot_top_get_val
get_table_extdouble_v calls aot_top_get_val
get_table_extdouble_vvect calls aot_top_get_val
get_table_integer calls aot_top_get_val
get_table_integer_v calls aot_top_get_val
get_table_integer_vvect calls aot_top_get_val
get_table_logical calls aot_top_get_val
get_table_logical_v calls aot_top_get_val
get_table_logical_vvect calls aot_top_get_val
get_table_long calls aot_top_get_val
get_table_long_v calls aot_top_get_val
get_table_long_vvect calls aot_top_get_val
get_table_quadruple calls aot_top_get_val
get_table_quadruple_v calls aot_top_get_val
get_table_quadruple_vvect calls aot_top_get_val
get_table_real calls aot_top_get_val
get_table_real_v calls aot_top_get_val
get_table_real_vvect calls aot_top_get_val
get_table_string calls aot_top_get_val
get_table_string_v calls aot_top_get_val
get_table_string_vvect calls aot_top_get_val
get_table_userdata calls aot_top_get_val
get_top_double_v calls aot_top_get_val
get_top_double_vvect calls aot_top_get_val
get_top_extdouble_v calls aot_top_get_val
get_top_extdouble_vvect calls aot_top_get_val
get_top_integer_v calls aot_top_get_val
get_top_integer_vvect calls aot_top_get_val
get_top_logical_v calls aot_top_get_val
get_top_logical_vvect calls aot_top_get_val
get_top_long_v calls aot_top_get_val
get_top_long_vvect calls aot_top_get_val
get_top_quadruple_v calls aot_top_get_val
get_top_quadruple_vvect calls aot_top_get_val
get_top_real_v calls aot_top_get_val
get_top_real_vvect calls aot_top_get_val
get_top_string_v calls aot_top_get_val
get_top_string_vvect calls aot_top_get_val
aot_get_val calls get_table_quadruple, get_table_extdouble, get_table_quadruple_vvect, get_table_quadruple_v, get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_extdouble_vvect, get_table_extdouble_v, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_table_get_val calls get_table_quadruple, get_table_extdouble, get_table_quadruple_vvect, get_table_quadruple_v, get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_extdouble_vvect, get_table_extdouble_v, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v