get_table_extdouble_v – Aotus
get_table_extdouble_v Subroutine
27 statements
Source File
private subroutine get_table_extdouble_v(val, ErrCode, L, thandle, key, pos, default)
This routine obtains a vectorial quantity with fixed length from a Lua table as a whole.
It is intented to ease the reading of vectors on the Fortran side by capsulating the parsing of the Lua table internally. Components which are not found are filled with the data given in the default vector. For each component an error code will be returned to indicate the success when reading it. If the vector is not defined at all, all components will be indicated as non-existent. Components, which are neither defined in the Lua script, nor in the default will be marked with the aoterr_Fatal flag.
Arguments
Type Intent Optional Attributes Name
real(kind=xdble_k), intent(out) :: val(:)
Vector read from the Lua table.
integer, intent(out) :: ErrCode(:)
Error code describing problems encountered in each of the components. This array has to have the same length as val.
type(flu_State) :: L
integer, intent(in), optional :: thandle
character(len=*), intent(in), optional :: key
Name of the variable (vector) to read.
integer, intent(in), optional :: pos
Position of the (vector) to read.
real(kind=xdble_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
Calls
Called by
Source Code
  subroutine get_table_extdouble_v(val, ErrCode, L, thandle, key, &
    &                              pos, default)
    type(flu_State) :: L !< Handle to the lua script
    integer, intent(in), optional :: thandle !< Handle of the parent table
    !> Vector read from the Lua table.
    real(kind=xdble_k), intent(out) :: val(:)
    !> Error code describing problems encountered in each of the components.
    !! This array has to have the same length as val.
    integer, intent(out) :: ErrCode(:)
    !> Name of the variable (vector) to read.
    character(len=*), intent(in), optional :: key
    !> Position of the (vector) to read.
    integer, intent(in), optional :: pos
    !> A default vector to use, if no proper definition is found.
    !! Components will be filled with the help of this default definition.
    real(kind=xdble_k), intent(in), optional :: default(:)
    logical :: valid_args
    integer :: toptype
    valid_args = .true.
    if (present(thandle)) then
      ! Get the requested value from the provided table
      call aot_table_push(L=L, thandle=thandle, &
        &                 key=key, pos=pos)
    else
      if (present(key)) then
        ! Get the requeseted global variable
        toptype = flu_getglobal(L, key)
      else
        valid_args = .false.
      end if
    end if
    if (valid_args) then
      call aot_top_get_val(val, ErrCode, L, default)
    else
      ErrCode = ibSet(0, aoterr_NonExistent)
      ErrCode = ibSet(ErrCode, aoterr_Fatal)
    end if
  end subroutine get_table_extdouble_v
Call graph
get_table_extdouble_v calls aot_top_get_val, aot_table_push, flu_getglobal
aot_top_get_val calls aot_top_get_extdouble
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_getglobal calls lua_getglobal
flu_pushinteger calls flu_pushint, flu_pushlong
aot_top_get_extdouble calls flu_pop, flu_isnoneornil, flu_isnumber, flu_todouble
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_type calls lua_type
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_todouble calls lua_tonumberx
aot_get_val calls get_table_extdouble_v
aot_table_get_val calls get_table_extdouble_v