get_table_extdouble – Aotus
get_table_extdouble Subroutine
27 statements
Source File
private subroutine get_table_extdouble(val, ErrCode, L, thandle, key, pos, default)
Retrieve a extdouble precision real value from a table.
NOTE that Lua actually only provides double precision numbers, and this interface is merely a convenience for Fortran implementations with extdouble precision real numbers.
Arguments
Type Intent Optional Attributes Name
real(kind=xdble_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Key and pos are both optional, however at least one of them has to be supplied. The key takes precedence over the pos if both are given.
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
It allows the access to unnamed arrays in the Lua tables.
real(kind=xdble_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
Calls
Called by
Source Code
  subroutine get_table_extdouble(val, ErrCode, L, thandle, key, pos, &
    &                            default)
    type(flu_State) :: L !< Handle to the Lua script.
    !> Handle to the table to look the value up in.
    integer, intent(in), optional :: thandle
    !> Value of the table entry if it exists.
    real(kind=xdble_k), intent(out) :: val
    !> Error code to indicate what kind of problem might have occured.
    integer, intent(out) :: ErrCode
    !> Name of the entry to look for.
    !!
    !! Key and pos are both optional, however at least one of them has to be
    !! supplied.
    !! The key takes precedence over the pos if both are given.
    character(len=*), intent(in), optional :: key
    !> Position of the entry to look for in the table.
    !!
    !! It allows the access to unnamed arrays in the Lua tables.
    integer, intent(in), optional :: pos
    !> Some default value, that should be used, if the variable is not set in
    !! the Lua script.
    real(kind=xdble_k), intent(in), optional :: default
    logical :: valid_args
    integer :: toptype
    valid_args = .true.
    if (present(thandle)) then
      call aot_table_push(L=L, thandle=thandle, &
        &                 key=key, pos=pos      )
    else
      if (present(key)) then
        toptype = flu_getglobal(L, key)
      else
        valid_args = .false.
      end if
    end if
    if (valid_args) then
      call aot_top_get_val(val, ErrCode, L, default)
    else
      ErrCode = ibSet(0, aoterr_NonExistent)
      ErrCode = ibSet(ErrCode, aoterr_Fatal)
    end if
  end subroutine get_table_extdouble
Call graph
get_table_extdouble calls aot_top_get_val, aot_table_push, flu_getglobal
aot_top_get_val calls aot_top_get_extdouble
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_getglobal calls lua_getglobal
flu_pushinteger calls flu_pushint, flu_pushlong
aot_top_get_extdouble calls flu_pop, flu_isnoneornil, flu_isnumber, flu_todouble
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_type calls lua_type
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_todouble calls lua_tonumberx
aot_get_val calls get_table_extdouble
aot_table_get_val calls get_table_extdouble