open_config_chunk – Aotus
open_config_chunk Subroutine
15 statements
Source File
public subroutine open_config_chunk(L, chunk, ErrCode, ErrString)
Subroutine to load and execute a script given in a string.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle to the Lua script
character(len=*), intent(in) :: chunk
String with Lua code to load.
integer, intent(out), optional :: ErrCode
Error code returned by Lua during loading or executing the file.
This optional parameter might be used to react on errors in the calling side. If neither ErrCode nor ErrString are given, this subroutine will stop the program execution and print the error message from Lua to the stdout.
character(len=*), intent(out), optional :: ErrString
Obtained error description from the Lua stack.
This optional argument holds the Lua error message in case something went wrong. It can be used to provide some feedback to the user in the calling routine. If neither ErrCode nor ErrString are provided, open_config() will print the error message and stop program execution.
Calls
Source Code
  subroutine open_config_chunk(L, chunk, ErrCode, ErrString)
    type(flu_State) :: L !! Handle to the Lua script
    !> String with Lua code to load.
    character(len=*), intent(in) :: chunk
    !> Error code returned by Lua during loading or executing the file.
    !!
    !! This optional parameter might be used to react on errors in the calling
    !! side. If neither ErrCode nor ErrString are given, this subroutine will
    !! stop the program execution and print the error message from Lua to the
    !! stdout.
    integer, intent(out), optional :: ErrCode
    !> Obtained error description from the Lua stack.
    !!
    !! This optional argument holds the Lua error message in case something
    !! went wrong. It can be used to provide some feedback to the user in the
    !! calling routine. If neither ErrCode nor ErrString are provided,
    !! open_config() will print the error message and stop program execution.
    character(len=*), intent(out), optional :: ErrString
    integer :: err
    if (.not.flu_isopen(L)) L = fluL_newstate()
    err = fluL_loadstring(L, chunk)
    call aot_err_handler(L, err, 'Cannot load chunk:', ErrString, ErrCode)
    if (err == 0) then
      call fluL_openlibs(L)
      err = flu_pcall(L, 0, 0, 0)
      call aot_err_handler(L, err, 'Cannot run chunk:', ErrString, ErrCode)
    end if
  end subroutine open_config_chunk
Call graph
open_config_chunk calls aot_err_handler, flu_isopen, flu_pcall, flul_loadstring, flul_newstate, flul_openlibs
aot_err_handler calls flu_tolstring
flu_pcall calls lua_pcallk
flul_loadstring calls lual_loadstring
flul_newstate calls lual_newstate
flul_openlibs calls lual_openlibs
flu_tolstring calls lua_tolstring