aot_fun_put – Aotus
aot_fun_put Interface
4 statements
Source File
public interface aot_fun_put
Put an argument into the lua function.
Arguments have to be in order, first put the first argument then the second and so on. Here we add support for extdouble precision numbers
Calls
Module Procedures
private subroutine aot_fun_put_extdouble(L, fun, arg)
Put an argument of type extended double into the list of arguments for the function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
type(aot_fun_type) :: fun
Handle of the function, this argument should be put into.
real(kind=xdble_k), intent(in) :: arg
Actual argument to hand over to the Lua function.
private subroutine aot_fun_put_extdouble_v(L, fun, arg)
Put an array of extended doubles into the list of arguments for the function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
type(aot_fun_type) :: fun
Handle of the function, this argument should be put into.
real(kind=xdble_k), intent(in) :: arg(:)
Actual argument to hand over to the Lua function.
Call graph
aot_fun_put calls aot_fun_put_extdouble, aot_fun_put_extdouble_v
aot_fun_put_extdouble calls flu_pushnumber, flu_pushvalue, flu_settop
aot_fun_put_extdouble_v calls aot_table_from_1darray, flu_pushvalue, flu_settop
aot_table_from_1darray calls create_1darray_extdouble
flu_pushnumber calls flu_pushdouble, flu_pushreal
flu_pushvalue calls lua_pushvalue
flu_settop calls lua_settop
create_1darray_extdouble calls flu_pushnumber, flu_pushinteger, flu_createtable, flu_gettop, flu_settable
flu_pushdouble calls lua_pushnumber
flu_pushreal calls lua_pushnumber
flu_pushinteger calls flu_pushint, flu_pushlong
flu_createtable calls lua_createtable
flu_gettop calls lua_gettop
flu_settable calls lua_settable
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger