aot_table_get_val – Aotus
aot_table_get_val Interface
9 statements
Source File
public interface aot_table_get_val
Get a value from a table.
First, the given key is looked up, if this fails, the value at the given position is looked up, and if this also fails, the default value is returned. Positional addressing is only valid, as long, as no value was provided by an explicit key in the list before the entry in question.
Calls
Module Procedures
private subroutine get_table_real(val, ErrCode, L, thandle, key, pos, default)
Retrieve a single precision real value from a table.
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
real(kind=single_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_double(val, ErrCode, L, thandle, key, pos, default)
Retrieve a double precision real value from a table.
Arguments
Type Intent Optional Attributes Name
real(kind=double_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
real(kind=double_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_integer(val, ErrCode, L, thandle, key, pos, default)
Retrieve a default integer value from a table.
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
integer(kind=int_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_long(val, ErrCode, L, thandle, key, pos, default)
Retrieve a long integer value from a table.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
integer(kind=long_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_string(val, ErrCode, L, thandle, key, pos, default)
Retrieve a string from a table.
Arguments
Type Intent Optional Attributes Name
character(len=*) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
character(len=*), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_logical(val, ErrCode, L, thandle, key, pos, default)
Retrieve a logical value from a table.
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
logical, intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_userdata(val, ErrCode, L, thandle, key, pos, default)
Retrieve a userdata value (generic C pointer) from a table.
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
type(c_ptr), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
Call graph
aot_table_get_val calls get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata
get_table_double calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_integer calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_logical calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_long calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_real calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_string calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_userdata calls aot_top_get_val, aot_table_push, flu_getglobal
aot_top_get_val calls aot_top_get_extdouble
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_getglobal calls lua_getglobal
flu_pushinteger calls flu_pushint, flu_pushlong
aot_top_get_extdouble calls flu_pop, flu_isnoneornil, flu_isnumber, flu_todouble
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_type calls lua_type
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_todouble calls lua_tonumberx