aot_top_get_val – Aotus
aot_top_get_val Interface
9 statements
Source File
public interface aot_top_get_val
Get the value on top of the Lua API stack
This is the most basic operation to retrieve a value. It is also most flexible in the sense, that it does not matter how the value actually gets on top of the stack by previous Lua operations.
The interface looks like this: call aot_top_get_val(val, errCode, L, default). See for example aot_top_get_real for a more detailed description of the parameters.
aot_top_get_val can not be in the same generic interface as the other aot_get_val routines, as it results in ambiguities of the interfaces.
Note
The retrieved value will be popped from the Lua API stack.
Calls
Module Procedures
private subroutine aot_top_get_real(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a single precision real.
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
real(kind=single_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine aot_top_get_double(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a double precision real.
Arguments
Type Intent Optional Attributes Name
real(kind=double_k), intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
real(kind=double_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine aot_top_get_integer(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a default integer.
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
integer(kind=int_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine aot_top_get_long(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a single precision real.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
integer(kind=long_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine aot_top_get_string(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a single precision real.
Arguments
Type Intent Optional Attributes Name
character(len=*) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
character(len=*), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine aot_top_get_logical(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as a single precision real.
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
logical, intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine aot_top_get_userdata(val, ErrCode, L, default)
Interpret topmost entry on Lua stack as userdata.
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(out) :: val
Value of the Variable in the script
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script
type(c_ptr), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
Call graph
aot_top_get_val calls aot_top_get_double, aot_top_get_integer, aot_top_get_logical, aot_top_get_long, aot_top_get_real, aot_top_get_string, aot_top_get_userdata
aot_top_get_double calls flu_isnoneornil, flu_isnumber, flu_pop, flu_todouble
aot_top_get_integer calls flu_isnoneornil, flu_isnumber, flu_pop, flu_todouble
aot_top_get_logical calls flu_isboolean, flu_isnoneornil, flu_pop, flu_toboolean
aot_top_get_long calls flu_isnoneornil, flu_isnumber, flu_pop, flu_todouble
aot_top_get_real calls flu_isnoneornil, flu_isnumber, flu_pop, flu_tonumber
aot_top_get_string calls flu_isnoneornil, flu_isstring, flu_pop, flu_tolstring
aot_top_get_userdata calls flu_islightuserdata, flu_isnoneornil, flu_pop, flu_touserdata
flu_isboolean calls lua_type
flu_islightuserdata calls lua_type
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_isstring calls lua_isstring
flu_pop calls lua_settop
flu_toboolean calls lua_toboolean
flu_todouble calls lua_tonumberx
flu_tolstring calls lua_tolstring
flu_tonumber calls lua_tonumberx
flu_touserdata calls lua_touserdata