aot_top_get_val – Aotus
aot_top_get_val Interface
3 statements
Source File
public interface aot_top_get_val
Calls
Module Procedures
private subroutine get_top_extdouble_vvect(val, ErrCode, maxlength, L, default)
Arguments
Type Intent Optional Attributes Name
real(kind=xdble_k), intent(out), allocatable :: val(:)
Vector read from the Lua table, will have the same length as the table but not exceed maxlength, if provided.
integer, intent(out), allocatable :: ErrCode(:)
Error code describing problems encountered in each of the components. Will be allocated with the same length as the returned vector. If the complete vector is not given in the Lua script, and no default is provided, an zerosized array will be returned.
integer, intent(in) :: maxlength
Maximal length to allocate for the vector.
type(flu_State) :: L
real(kind=xdble_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
Call graph
aot_top_get_val calls get_top_extdouble_vvect, aot_top_get_extdouble
get_top_extdouble_vvect calls aot_top_get_val, aot_table_close, aot_table_first, aot_table_length, aot_table_top, flu_next
aot_table_close calls flu_settop
aot_table_first calls flu_next, flu_pushnil
aot_table_length calls aot_table_first, flu_next, flu_pop
aot_table_top calls flu_gettop, flu_istable, flu_pop
flu_next calls lua_next
aot_top_get_extdouble calls flu_pop, flu_isnoneornil, flu_isnumber, flu_todouble
flu_gettop calls lua_gettop
flu_istable calls lua_type
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_settop calls lua_settop
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_todouble calls lua_tonumberx