aot_push – Aotus
aot_push Interface
3 statements
Source File
public interface aot_push
Calls
Module Procedures
public subroutine aot_table_push(L, thandle, key, pos, toptype)
This subroutine tries to push the value of the entry given by key or pos within the table thandle onto the Lua stack.
Read more…
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look in.
character(len=*), intent(in), optional :: key
Name of the entry to push to the stack.
integer, intent(in), optional :: pos
Position of the entry to push to the stack.
integer, intent(out), optional :: toptype
Call graph
aot_push calls aot_table_push
aot_table_push calls flu_pushinteger, flu_getfield, flu_getglobal, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_pushinteger calls flu_pushint, flu_pushlong
flu_getfield calls lua_getfield
flu_getglobal calls lua_getglobal
flu_gettable calls lua_gettable
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_type calls lua_type
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger