aot_table_set_val – Aotus
aot_table_set_val Interface
3 statements
Source File
public interface aot_table_set_val
Set a value in a table.
The given value will be put at the entry named by key into the table provided in thandle. Alternatively you can also put the value by position into the table by providing the pos argument. If both, pos and key are provided, the key will be used. Though, both of them are optional, at least one of them has to be provided.
Calls
Called by
Module Procedures
private subroutine set_table_extdouble(val, L, thandle, key, pos)
Put a extdouble precision real value into a table.
Arguments
Type Intent Optional Attributes Name
real(kind=xdble_k), intent(in) :: val
Value of the table entry if it exists.
type(flu_State) :: L
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
Call graph
aot_table_set_val calls set_table_extdouble
set_table_extdouble calls flu_pushinteger, flu_pushnumber, flu_setfield, flu_settable
flu_pushinteger calls flu_pushint, flu_pushlong
flu_pushnumber calls flu_pushdouble, flu_pushreal
flu_setfield calls lua_setfield
flu_settable calls lua_settable
flu_pushdouble calls lua_pushnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_pushreal calls lua_pushnumber
aot_require_buffer calls aot_table_set_val