aot_table_from_1Darray – Aotus
aot_table_from_1Darray Interface
4 statements
Source File
public interface aot_table_from_1Darray
This interface enables the simple creation of uniform one dimensional arrays as tables in the Lua context.
It takes an one dimensional array of values and returns a thandle to identify the newly generated table.
Calls
Module Procedures
private subroutine create_1Darray_real(L, thandle, val)
This subroutine takes a one dimensional array, and puts it as a table into the Lua context.
Read more…
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle to the Lua script.
integer, intent(out) :: thandle
Handle to access the newly created table.
real(kind=single_k), intent(in) :: val(:)
Values to put into the new table.
private subroutine create_1Darray_double(L, thandle, val)
This subroutine takes a one dimensional array, and puts it as a table into the Lua context.
Read more…
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer, intent(out) :: thandle
Handle to access the newly created table.
real(kind=double_k), intent(in) :: val(:)
Values to put into the new table.
Call graph
aot_table_from_1darray calls create_1darray_double, create_1darray_real
create_1darray_double calls flu_pushinteger, flu_pushnumber, flu_createtable, flu_gettop, flu_settable
create_1darray_real calls flu_pushinteger, flu_pushnumber, flu_createtable, flu_gettop, flu_settable
flu_pushinteger calls flu_pushint, flu_pushlong
flu_pushnumber calls flu_pushdouble, flu_pushreal
flu_createtable calls lua_createtable
flu_gettop calls lua_gettop
flu_settable calls lua_settable
flu_pushdouble calls lua_pushnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_pushreal calls lua_pushnumber