aot_path_close – Aotus
aot_path_close Interface
4 statements
Source File
public interface aot_path_close
Calls
Module Procedures
private subroutine aot_path_close_fun(me, conf, fun, closeLua)
This routine closes function and all other tables opened along the path.
Arguments
Type Intent Optional Attributes Name
type(aot_path_type), intent(inout) :: me
The path object to open as a function
type(flu_State) :: conf
The flu_state handle, which is either opened according to the path, or used to open the path in.
type(aot_fun_type), intent(inout) :: fun
The opened function
logical, intent(in), optional :: closeLua
A flag to indicate, wether to close the Lua script, default is false.
private subroutine aot_path_close_table(me, conf, closeLua)
This routine closes all the table opened in aot_path_open_table.
Arguments
Type Intent Optional Attributes Name
type(aot_path_type), intent(inout) :: me
The path object to open as a function
type(flu_State) :: conf
The flu_state handle, which is either opened according to the path, or used to open the path in.
logical, intent(in), optional :: closeLua
A flag to indicate, wether to close the Lua script, default is false.
Call graph
aot_path_close calls aot_path_close_fun, aot_path_close_table
aot_path_close_fun calls aot_path_close_table, aot_fun_close
aot_path_close_table calls aot_table_close, close_config
aot_fun_close calls flu_settop
aot_table_close calls flu_settop
close_config calls flu_close
flu_close calls lua_close
flu_settop calls lua_settop