aot_top_get_val – Aotus
aot_top_get_val Interface
8 statements
Source File
public interface aot_top_get_val
Calls
Module Procedures
private subroutine get_top_real_v(val, ErrCode, L, default)
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(out) :: val(:)
Vector read from the Lua table.
integer, intent(out) :: ErrCode(:)
Error code describing problems encountered in each of the components. This array has to have the same length as val.
type(flu_State) :: L
Handle to the lua script
real(kind=single_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_top_double_v(val, ErrCode, L, default)
Arguments
Type Intent Optional Attributes Name
real(kind=double_k), intent(out) :: val(:)
Vector read from the Lua table.
integer, intent(out) :: ErrCode(:)
Error code describing problems encountered in each of the components. This array has to have the same length as val.
type(flu_State) :: L
Handle to the lua script
real(kind=double_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_top_integer_v(val, ErrCode, L, default)
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(out) :: val(:)
Vector read from the Lua table.
integer, intent(out) :: ErrCode(:)
Error code describing problems encountered in each of the components. This array has to have the same length as val.
type(flu_State) :: L
Handle to the lua script
integer(kind=int_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_top_long_v(val, ErrCode, L, default)
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(out) :: val(:)
Vector read from the Lua table.
integer, intent(out) :: ErrCode(:)
Error code describing problems encountered in each of the components. This array has to have the same length as val.
type(flu_State) :: L
Handle to the lua script
integer(kind=long_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_top_logical_v(val, ErrCode, L, default)
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: val(:)
Vector read from the Lua table.
integer, intent(out) :: ErrCode(:)
Error code describing problems encountered in each of the components. This array has to have the same length as val.
type(flu_State) :: L
Handle to the lua script
logical, intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_top_string_v(val, ErrCode, L, default)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(out) :: val(:)
Vector read from the Lua table.
integer, intent(out) :: ErrCode(:)
Error code describing problems encountered in each of the components. This array has to have the same length as val.
type(flu_State) :: L
Handle to the lua script
character(len=*), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
Call graph
aot_top_get_val calls get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v, aot_top_get_extdouble
get_top_double_v calls aot_top_get_val, aot_table_close, aot_table_first, aot_table_length, aot_table_top, flu_next
get_top_integer_v calls aot_top_get_val, aot_table_close, aot_table_first, aot_table_length, aot_table_top, flu_next
get_top_logical_v calls aot_top_get_val, aot_table_close, aot_table_first, aot_table_length, aot_table_top, flu_next
get_top_long_v calls aot_top_get_val, aot_table_close, aot_table_first, aot_table_length, aot_table_top, flu_next
get_top_real_v calls aot_top_get_val, aot_table_close, aot_table_first, aot_table_length, aot_table_top, flu_next
get_top_string_v calls aot_top_get_val, aot_table_close, aot_table_first, aot_table_length, aot_table_top, flu_next
aot_table_close calls flu_settop
aot_table_first calls flu_next, flu_pushnil
aot_table_length calls aot_table_first, flu_next, flu_pop
aot_table_top calls flu_gettop, flu_istable, flu_pop
flu_next calls lua_next
aot_top_get_extdouble calls flu_pop, flu_isnoneornil, flu_isnumber, flu_todouble
flu_gettop calls lua_gettop
flu_istable calls lua_type
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_settop calls lua_settop
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_todouble calls lua_tonumberx