aot_table_set_val – Aotus
aot_table_set_val Interface
9 statements
Source File
public interface aot_table_set_val
Set a value in a table.
The given value will be put at the entry named by key into the table provided in thandle. Alternatively, you can also put the value by position into the table by providing the pos argument. If both, pos and key are provided, the key will be used. Though, both of them are optional, at least one of them has to be provided.
Calls
Module Procedures
private subroutine set_table_real(val, L, thandle, key, pos)
Put a single precision real value into a table.
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(in) :: val
Value of the table entry if it exists.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
private subroutine set_table_double(val, L, thandle, key, pos)
Put a double precision real value into a table.
Arguments
Type Intent Optional Attributes Name
real(kind=double_k), intent(in) :: val
Value of the table entry if it exists.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
private subroutine set_table_integer(val, L, thandle, key, pos)
Put a default integer value into a table.
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(in) :: val
Value of the table entry if it exists.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
private subroutine set_table_long(val, L, thandle, key, pos)
Put a long integer value into a table.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(in) :: val
Value of the table entry if it exists.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
private subroutine set_table_string(val, L, thandle, key, pos)
Put a string value into a table.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: val
Value to set in the table.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to set.
Read more…
integer, intent(in), optional :: pos
Position of the entry to set in the table.
Read more…
private subroutine set_table_logical(val, L, thandle, key, pos)
Put a logical value into a table.
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: val
Value to set in the table.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to set.
Read more…
integer, intent(in), optional :: pos
Position of the entry to set in the table.
Read more…
private subroutine set_table_userdata(val, L, thandle, key, pos)
Put user-data pointer into a table.
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in) :: val
Pointer to set in the table.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in) :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to set.
Read more…
integer, intent(in), optional :: pos
Position of the entry to set in the table.
Read more…
Call graph
aot_table_set_val calls set_table_double, set_table_integer, set_table_logical, set_table_long, set_table_real, set_table_string, set_table_userdata
set_table_double calls flu_pushinteger, flu_pushnumber, flu_setfield, flu_settable
set_table_integer calls flu_pushinteger, flu_setfield, flu_settable
set_table_logical calls flu_pushinteger, flu_pushboolean, flu_setfield, flu_settable
set_table_long calls flu_pushinteger, flu_setfield, flu_settable
set_table_real calls flu_pushinteger, flu_pushnumber, flu_setfield, flu_settable
set_table_string calls flu_pushinteger, flu_pushstring, flu_setfield, flu_settable
set_table_userdata calls flu_pushinteger, flu_pushlightuserdata, flu_setfield, flu_settable
flu_pushinteger calls flu_pushint, flu_pushlong
flu_pushnumber calls flu_pushdouble, flu_pushreal
flu_pushboolean calls lua_pushboolean
flu_pushlightuserdata calls lua_pushlightuserdata
flu_pushstring calls lua_pushlstring
flu_setfield calls lua_setfield
flu_settable calls lua_settable
flu_pushdouble calls lua_pushnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_pushreal calls lua_pushnumber