aot_out_val – Aotus
aot_out_val Interface
14 statements
Source File
public interface aot_out_val
Put Fortran intrinsic types into the script.
Scalar values and one-dimensional arrays are supported. Supported data-types are - integer - integer(kind=long_k) - real - real(kind=double_k) - logical - character(len=*) complex values are not supported, as they are indistinguishable from arrays with two entries on the Lua side.
Calls
Module Procedures
private subroutine aot_out_val_int(put_conf, val, vname, advance_previous)
Put integer variables into the Lua script.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
integer(kind=int_k), intent(in) :: val
character(len=*), intent(in), optional :: vname
logical, intent(in), optional :: advance_previous
private subroutine aot_out_val_long(put_conf, val, vname, advance_previous)
Put long variables into the Lua script.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
integer(kind=long_k), intent(in) :: val
character(len=*), intent(in), optional :: vname
logical, intent(in), optional :: advance_previous
private subroutine aot_out_val_real(put_conf, val, vname, advance_previous)
Put real variables into the Lua script.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
real(kind=single_k), intent(in) :: val
character(len=*), intent(in), optional :: vname
logical, intent(in), optional :: advance_previous
private subroutine aot_out_val_double(put_conf, val, vname, advance_previous)
Put double variables into the Lua script.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
real(kind=double_k), intent(in) :: val
character(len=*), intent(in), optional :: vname
logical, intent(in), optional :: advance_previous
private subroutine aot_out_val_logical(put_conf, val, vname, advance_previous)
Put logical variables into the Lua script.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
logical, intent(in) :: val
character(len=*), intent(in), optional :: vname
logical, intent(in), optional :: advance_previous
private subroutine aot_out_val_string(put_conf, val, vname, advance_previous)
Put string variables into the Lua script.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
character(len=*), intent(in) :: val
character(len=*), intent(in), optional :: vname
logical, intent(in), optional :: advance_previous
private subroutine aot_out_val_arr_int(put_conf, val, vname, advance_previous, max_per_line)
This is a vectorized version of the value output.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
Lua script to write the array into.
integer(kind=int_k), intent(in) :: val(:)
Actual data to write into the script
character(len=*), intent(in), optional :: vname
Name for this array
logical, intent(in), optional :: advance_previous
Flag if this array should be put on the same line as the last entry of the parent table.
integer, intent(in), optional :: max_per_line
Maximal number of entries to put into a single line. Defaults to 8.
private subroutine aot_out_val_arr_long(put_conf, val, vname, advance_previous, max_per_line)
This is a vectorized version of the value output.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
Lua script to write the array into.
integer(kind=long_k), intent(in) :: val(:)
Actual data to write into the script
character(len=*), intent(in), optional :: vname
Name for this array
logical, intent(in), optional :: advance_previous
Flag if this array should be put on the same line as the last entry of the parent table.
integer, intent(in), optional :: max_per_line
Maximal number of entries to put into a single line. Defaults to 8.
private subroutine aot_out_val_arr_real(put_conf, val, vname, advance_previous, max_per_line)
This is a vectorized version of the value output.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
Lua script to write the array into.
real(kind=single_k), intent(in) :: val(:)
Actual data to write into the script
character(len=*), intent(in), optional :: vname
Name for this array
logical, intent(in), optional :: advance_previous
Flag if this array should be put on the same line as the last entry of the parent table.
integer, intent(in), optional :: max_per_line
Maximal number of entries to put into a single line. Defaults to 5.
private subroutine aot_out_val_arr_double(put_conf, val, vname, advance_previous, max_per_line)
This is a vectorized version of the value output.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
Lua script to write the array into.
real(kind=double_k), intent(in) :: val(:)
Actual data to write into the script
character(len=*), intent(in), optional :: vname
Name for this array
logical, intent(in), optional :: advance_previous
Flag if this array should be put on the same line as the last entry of the parent table.
integer, intent(in), optional :: max_per_line
Maximal number of entries to put into a single line. Defaults to 3.
private subroutine aot_out_val_arr_logical(put_conf, val, vname, advance_previous, max_per_line)
This is a vectorized version of the value output.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
Lua script to write the array into.
logical, intent(in) :: val(:)
Actual data to write into the script
character(len=*), intent(in), optional :: vname
Name for this array
logical, intent(in), optional :: advance_previous
Flag if this array should be put on the same line as the last entry of the parent table.
integer, intent(in), optional :: max_per_line
Maximal number of entries to put into a single line. Defaults to 10.
private subroutine aot_out_val_arr_string(put_conf, val, vname, advance_previous, max_per_line)
This is a vectorized version of the value output.
Read more…
Arguments
Type Intent Optional Attributes Name
type(aot_out_type), intent(inout) :: put_conf
Lua script to write the array into.
character(len=*), intent(in) :: val(:)
Actual data to write into the script
character(len=*), intent(in), optional :: vname
Name for this array
logical, intent(in), optional :: advance_previous
Flag if this array should be put on the same line as the last entry of the parent table.
integer, intent(in), optional :: max_per_line
Maximal number of entries to put into a single line. Defaults to 1.
Call graph
aot_out_val calls aot_out_val_arr_double, aot_out_val_arr_int, aot_out_val_arr_logical, aot_out_val_arr_long, aot_out_val_arr_real, aot_out_val_arr_string, aot_out_val_double, aot_out_val_int, aot_out_val_logical, aot_out_val_long, aot_out_val_real, aot_out_val_string, aot_out_val_arr_extdouble, aot_out_val_extdouble
aot_out_val_arr_double calls aot_out_val, aot_out_close_table, aot_out_open_table
aot_out_val_arr_int calls aot_out_val, aot_out_close_table, aot_out_open_table
aot_out_val_arr_logical calls aot_out_val, aot_out_close_table, aot_out_open_table
aot_out_val_arr_long calls aot_out_val, aot_out_close_table, aot_out_open_table
aot_out_val_arr_real calls aot_out_val, aot_out_close_table, aot_out_open_table
aot_out_val_arr_string calls aot_out_val, aot_out_close_table, aot_out_open_table
aot_out_val_double calls aot_out_breakline
aot_out_val_int calls aot_out_breakline
aot_out_val_logical calls aot_out_breakline
aot_out_val_long calls aot_out_breakline
aot_out_val_real calls aot_out_breakline
aot_out_val_string calls aot_out_breakline
aot_out_open_table calls aot_out_breakline
aot_out_val_arr_extdouble calls aot_out_val, aot_out_close_table, aot_out_open_table
aot_out_val_extdouble calls aot_out_breakline