aot_get_val – Aotus
aot_get_val Interface
9 statements
Source File
public interface aot_get_val
Get a value from the Lua script.
This is the central interface to retrieve values from a Lua script, its general shape looks like call aot_{top}_get_val(<outputs>, <id>, default). Where the "outputs" are val and errCode. While "id" is at least the Lua context L. For global variables there has to be a key to identify the variable.
The errCode returns an error code with various bits set for different errors that might happen while retrieving the variable. They can be checked by btest and the different error codes are:
aoterr_Fatal: Something went irrecoverably wrong
aoterr_NonExistent: The requested variable is not set in the Lua script
aoterr_WrongType: The requested variable in the Lua script does not match the requested data type
For example a check for a fatal error can be done by btest(errCode, aoterr_fatal).
For the access to global variables in the Lua script the interface therefore, looks like: call aot_get_val(val, errCode, L, key, default).
The interface to access table values looks like: call aot_get_val(val, errCode, L, thandle, key, pos, default). Position pos and key are both optional, but one of them has to be provided. If both are provided the key takes precedence over the pos, and the pos will only be tried if the access to the key fails. See for example get_table_real for a more detailed description of the parameters.
Note
Positional addressing only works intuitively as long as there have been no entries specified by keys in the table. This kind of resembles the behavior of Fortran interfaces with named or unnamed arguments, as soon as you provide a name, all following arguments have to be given by key also. Just stick to this rule for the Lua tables as well to avoid too much headache. The reason for this is, that positional addressing in Lua refers only to the unnamed entries of the tables.
Calls
Module Procedures
private subroutine get_table_real(val, ErrCode, L, thandle, key, pos, default)
Retrieve a single precision real value from a table.
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
real(kind=single_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_double(val, ErrCode, L, thandle, key, pos, default)
Retrieve a double precision real value from a table.
Arguments
Type Intent Optional Attributes Name
real(kind=double_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
real(kind=double_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_integer(val, ErrCode, L, thandle, key, pos, default)
Retrieve a default integer value from a table.
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
integer(kind=int_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_long(val, ErrCode, L, thandle, key, pos, default)
Retrieve a long integer value from a table.
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
integer(kind=long_k), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_string(val, ErrCode, L, thandle, key, pos, default)
Retrieve a string from a table.
Arguments
Type Intent Optional Attributes Name
character(len=*) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
character(len=*), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_logical(val, ErrCode, L, thandle, key, pos, default)
Retrieve a logical value from a table.
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
logical, intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
private subroutine get_table_userdata(val, ErrCode, L, thandle, key, pos, default)
Retrieve a userdata value (generic C pointer) from a table.
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(out) :: val
Value of the table entry if it exists.
integer, intent(out) :: ErrCode
Error code to indicate what kind of problem might have occured.
type(flu_State) :: L
Handle to the Lua script.
integer, intent(in), optional :: thandle
Handle to the table to look the value up in.
character(len=*), intent(in), optional :: key
Name of the entry to look for.
Read more…
integer, intent(in), optional :: pos
Position of the entry to look for in the table.
Read more…
type(c_ptr), intent(in), optional :: default
Some default value, that should be used, if the variable is not set in the Lua script.
Call graph
aot_get_val calls get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata
get_table_double calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_integer calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_logical calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_long calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_real calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_string calls aot_top_get_val, aot_table_push, flu_getglobal
get_table_userdata calls aot_top_get_val, aot_table_push, flu_getglobal
aot_top_get_val calls aot_top_get_extdouble
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_getglobal calls lua_getglobal
flu_pushinteger calls flu_pushint, flu_pushlong
aot_top_get_extdouble calls flu_pop, flu_isnoneornil, flu_isnumber, flu_todouble
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_type calls lua_type
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_todouble calls lua_tonumberx