aot_fun_put – Aotus
aot_fun_put Interface
7 statements
Source File
public interface aot_fun_put
Put an argument into the lua function.
Arguments have to be in order, first put the first argument then the second and so on. Currently only real number arguments are supported.
Calls
Module Procedures
private subroutine aot_fun_put_top(L, fun)
Put the top of the stack as argument into the list of arguments for the function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
type(aot_fun_type) :: fun
Handle of the function, this argument should be put into.
private subroutine aot_fun_put_double(L, fun, arg)
Put an argument of type double into the list of arguments for the function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
type(aot_fun_type) :: fun
Handle of the function, this argument should be put into.
real(kind=double_k), intent(in) :: arg
Actual argument to hand over to the Lua function.
private subroutine aot_fun_put_single(L, fun, arg)
Put an argument of type single into the list of arguments for the function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
type(aot_fun_type) :: fun
Handle of the function, this argument should be put into.
real(kind=single_k), intent(in) :: arg
Actual argument to hand over to the Lua function.
private subroutine aot_fun_put_double_v(L, fun, arg)
Put an array of doubles into the list of arguments for the function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
type(aot_fun_type) :: fun
Handle of the function, this argument should be put into.
real(kind=double_k), intent(in) :: arg(:)
Actual argument to hand over to the Lua function.
private subroutine aot_fun_put_single_v(L, fun, arg)
Put an array of singles into the list of arguments for the function.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
type(aot_fun_type) :: fun
Handle of the function, this argument should be put into.
real(kind=single_k), intent(in) :: arg(:)
Actual argument to hand over to the Lua function.
Call graph
aot_fun_put calls aot_fun_put_double, aot_fun_put_double_v, aot_fun_put_single, aot_fun_put_single_v, aot_fun_put_top
aot_fun_put_double calls flu_pushnumber, flu_pushvalue, flu_settop
aot_fun_put_double_v calls aot_table_from_1darray, flu_pushvalue, flu_settop
aot_fun_put_single calls flu_pushnumber, flu_pushvalue, flu_settop
aot_fun_put_single_v calls aot_table_from_1darray, flu_pushvalue, flu_settop
aot_fun_put_top calls flu_gettop, flu_insert
aot_table_from_1darray calls create_1darray_extdouble
flu_pushnumber calls flu_pushdouble, flu_pushreal
flu_gettop calls lua_gettop
flu_insert calls lua_rotate
flu_pushvalue calls lua_pushvalue
flu_settop calls lua_settop
create_1darray_extdouble calls flu_pushnumber, flu_gettop, flu_pushinteger, flu_createtable, flu_settable
flu_pushdouble calls lua_pushnumber
flu_pushreal calls lua_pushnumber
flu_pushinteger calls flu_pushint, flu_pushlong
flu_createtable calls lua_createtable
flu_settable calls lua_settable
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger