aot_get_val – Aotus
aot_get_val Interface
3 statements
Source File
public interface aot_get_val
Use these routines to obtain a vector whose length is unknown.
Arrays will be allocated as needed to read the data from the Lua script with these routines. A maximal length has to be specified to limit the allocated memory by these routines (and make the interfaces distinguishable).
Calls
Module Procedures
private subroutine get_table_extdouble_vvect(val, ErrCode, maxlength, L, thandle, key, pos, default)
This routine obtains a vectorial quantity with variable length from a Lua table as a whole.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=xdble_k), intent(out), allocatable :: val(:)
Vector read from the Lua table, will have the same length as the table but not exceed maxlength, if provided.
integer, intent(out), allocatable :: ErrCode(:)
Error code describing problems encountered in each of the components. Will be allocated with the same length as the returned vector. If the complete vector is not given in the Lua script, and no default is provided, an zerosized array will be returned.
integer, intent(in) :: maxlength
Maximal length to allocate for the vector.
type(flu_State) :: L
integer, intent(in), optional :: thandle
character(len=*), intent(in), optional :: key
Name of the variable (vector) to read.
integer, intent(in), optional :: pos
Position of the (vector) to read.
real(kind=xdble_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
Call graph
aot_get_val calls get_table_extdouble_vvect
get_table_extdouble_vvect calls aot_top_get_val, aot_table_push, flu_getglobal
aot_top_get_val calls aot_top_get_extdouble
aot_table_push calls flu_getglobal, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_getglobal calls lua_getglobal
flu_pushinteger calls flu_pushint, flu_pushlong
aot_top_get_extdouble calls flu_pop, flu_isnoneornil, flu_isnumber, flu_todouble
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_type calls lua_type
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
flu_todouble calls lua_tonumberx