aot_table_get_val – Aotus
aot_table_get_val Interface
8 statements
Source File
public interface aot_table_get_val
Calls
Module Procedures
private subroutine get_table_real_vvect(val, ErrCode, maxlength, L, thandle, key, pos, default)
This routine obtains a vectorial quantity with variable length from a Lua table as a whole.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=single_k), intent(out), allocatable :: val(:)
Vector read from the Lua table, will have the same length as the table but not exceed maxlength, if provided.
integer, intent(out), allocatable :: ErrCode(:)
Error code describing problems encountered in each of the components. Will be allocated with the same length as the returned vector. If the complete vector is not given in the Lua script, and no default is provided, an zerosized array will be returned.
integer, intent(in) :: maxlength
Maximal length to allocate for the vector.
type(flu_State) :: L
Handle to the lua script
integer, intent(in), optional :: thandle
Handle of the parent table
character(len=*), intent(in), optional :: key
Name of the variable (vector) to read.
integer, intent(in), optional :: pos
Position of the (vector) to read.
real(kind=single_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_table_double_vvect(val, ErrCode, maxlength, L, thandle, key, pos, default)
This routine obtains a vectorial quantity with variable length from a Lua table as a whole.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=double_k), intent(out), allocatable :: val(:)
Vector read from the Lua table, will have the same length as the table but not exceed maxlength, if provided.
integer, intent(out), allocatable :: ErrCode(:)
Error code describing problems encountered in each of the components. Will be allocated with the same length as the returned vector. If the complete vector is not given in the Lua script, and no default is provided, an zerosized array will be returned.
integer, intent(in) :: maxlength
Maximal length to allocate for the vector.
type(flu_State) :: L
Handle to the lua script
integer, intent(in), optional :: thandle
Handle of the parent table
character(len=*), intent(in), optional :: key
Name of the variable (vector) to read.
integer, intent(in), optional :: pos
Position of the (vector) to read.
real(kind=double_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_table_integer_vvect(val, ErrCode, maxlength, L, thandle, key, pos, default)
This routine obtains a vectorial quantity with variable length from a Lua table as a whole.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=int_k), intent(out), allocatable :: val(:)
Vector read from the Lua table, will have the same length as the table but not exceed maxlength, if provided.
integer, intent(out), allocatable :: ErrCode(:)
Error code describing problems encountered in each of the components. Will be allocated with the same length as the returned vector. If the complete vector is not given in the Lua script, and no default is provided, an zerosized array will be returned.
integer, intent(in) :: maxlength
Maximal length to allocate for the vector.
type(flu_State) :: L
Handle to the lua script
integer, intent(in), optional :: thandle
Handle of the parent table
character(len=*), intent(in), optional :: key
Name of the variable (vector) to read.
integer, intent(in), optional :: pos
Position of the (vector) to read.
integer(kind=int_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_table_long_vvect(val, ErrCode, maxlength, L, thandle, key, pos, default)
This routine obtains a vectorial quantity with variable length from a Lua table as a whole.
Read more…
Arguments
Type Intent Optional Attributes Name
integer(kind=long_k), intent(out), allocatable :: val(:)
Vector read from the Lua table, will have the same length as the table but not exceed maxlength, if provided.
integer, intent(out), allocatable :: ErrCode(:)
Error code describing problems encountered in each of the components. Will be allocated with the same length as the returned vector. If the complete vector is not given in the Lua script, and no default is provided, an zerosized array will be returned.
integer, intent(in) :: maxlength
Maximal length to allocate for the vector.
type(flu_State) :: L
Handle to the lua script
integer, intent(in), optional :: thandle
Handle of the parent table
character(len=*), intent(in), optional :: key
Name of the variable (vector) to read.
integer, intent(in), optional :: pos
Position of the (vector) to read.
integer(kind=long_k), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_table_logical_vvect(val, ErrCode, maxlength, L, thandle, key, pos, default)
This routine obtains a vectorial quantity with variable length from a Lua table as a whole.
Read more…
Arguments
Type Intent Optional Attributes Name
logical, intent(out), allocatable :: val(:)
Vector read from the Lua table, will have the same length as the table but not exceed maxlength, if provided.
integer, intent(out), allocatable :: ErrCode(:)
Error code describing problems encountered in each of the components. Will be allocated with the same length as the returned vector. If the complete vector is not given in the Lua script, and no default is provided, an zerosized array will be returned.
integer, intent(in) :: maxlength
Maximal length to allocate for the vector.
type(flu_State) :: L
Handle to the lua script
integer, intent(in), optional :: thandle
Handle of the parent table
character(len=*), intent(in), optional :: key
Name of the variable (vector) to read.
integer, intent(in), optional :: pos
Position of the (vector) to read.
logical, intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
private subroutine get_table_string_vvect(val, ErrCode, maxlength, L, thandle, key, pos, default)
This routine obtains a vectorial quantity with variable length from a Lua table as a whole.
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(out), allocatable :: val(:)
Vector read from the Lua table, will have the same length as the table but not exceed maxlength, if provided.
integer, intent(out), allocatable :: ErrCode(:)
Error code describing problems encountered in each of the components. Will be allocated with the same length as the returned vector. If the complete vector is not given in the Lua script, and no default is provided, an zerosized array will be returned.
integer, intent(in) :: maxlength
Maximal length to allocate for the vector.
type(flu_State) :: L
Handle to the lua script
integer, intent(in), optional :: thandle
Handle of the parent table
character(len=*), intent(in), optional :: key
Name of the variable (vector) to read.
integer, intent(in), optional :: pos
Position of the (vector) to read.
character(len=*), intent(in), optional :: default(:)
A default vector to use, if no proper definition is found. Components will be filled with the help of this default definition.
Call graph
aot_table_get_val calls get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect
get_table_double_vvect calls aot_top_get_val, aot_type_of
get_table_integer_vvect calls aot_top_get_val, aot_type_of
get_table_logical_vvect calls aot_top_get_val, aot_type_of
get_table_long_vvect calls aot_top_get_val, aot_type_of
get_table_real_vvect calls aot_top_get_val, aot_type_of
get_table_string_vvect calls aot_top_get_val, aot_type_of
aot_top_get_val calls aot_top_get_extdouble
aot_type_of calls aot_table_push, flu_getglobal, flu_type
aot_table_push calls flu_getglobal, flu_type, flu_pushinteger, flu_getfield, flu_gettable, flu_pop, flu_pushnil
aot_top_get_extdouble calls flu_isnoneornil, flu_isnumber, flu_pop, flu_todouble
flu_getglobal calls lua_getglobal
flu_type calls lua_type
flu_pushinteger calls flu_pushint, flu_pushlong
flu_getfield calls lua_getfield
flu_gettable calls lua_gettable
flu_isnoneornil calls lua_type
flu_isnumber calls lua_isnumber
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_todouble calls lua_tonumberx
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger