aot_fun_open – Aotus
aot_fun_open Interface
4 statements
Source File
public interface aot_fun_open
Open a Lua function for evaluation.
After it is opened, arguments might be put into the function, and it might be executed. Execution might be repeated for an arbitrary number of iterations, to retrieve more than one evaluation of a single function, before closing it again with aot_fun_close.
Calls
Called by
Module Procedures
private subroutine aot_fun_table(L, parent, fun, key, pos)
Get a function defined as component of a table.
Read more…
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
integer, intent(in), optional :: parent
Handle to the table to look in for the function.
type(aot_fun_type), intent(out) :: fun
Returned handle, providing access to the function.
character(len=*), intent(in), optional :: key
Name of the function to look up in the table.
integer, intent(in), optional :: pos
Position of the function to look up in the table.
private subroutine aot_fun_ref(L, fun, ref)
Get a function from a previously defned Lua reference.
Read more…
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
Handle for the Lua script.
type(aot_fun_type), intent(out) :: fun
Returned handle, providing access to the function.
integer, intent(in) :: ref
Lua reference to the function.
Call graph
aot_fun_open calls aot_fun_ref, aot_fun_table
aot_fun_ref calls aot_fun_top, aot_reference_to_top
aot_fun_table calls aot_fun_top, aot_table_push
aot_fun_top calls flu_gettop, flu_isfunction, flu_pushvalue, flu_topointer
aot_reference_to_top calls flu_rawgeti
aot_table_push calls flu_pushinteger, flu_getfield, flu_getglobal, flu_gettable, flu_pop, flu_pushnil, flu_type
flu_pushinteger calls flu_pushint, flu_pushlong
flu_getfield calls lua_getfield
flu_getglobal calls lua_getglobal
flu_gettable calls lua_gettable
flu_gettop calls lua_gettop
flu_isfunction calls lua_type
flu_pop calls lua_settop
flu_pushnil calls lua_pushnil
flu_pushvalue calls lua_pushvalue
flu_rawgeti calls lua_rawgeti
flu_topointer calls lua_topointer
flu_type calls lua_type
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
aot_path_open_fun calls aot_fun_open
aot_path_open calls aot_path_open_fun