dump_lua_toBuf – Aotus
dump_lua_toBuf Interface
9 statements
Source File
interface
Called by
public function dump_lua_toBuf(L, length, ierr) bind(c, name='dump_lua_toBuf')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
integer(kind=c_int) :: length
integer(kind=c_int) :: ierr
Return Value type(c_ptr)
Call graph
flu_dump_tobuf calls dump_lua_tobuf
flu_dump calls flu_dump_tobuf
aot_file_to_buffer calls flu_dump
open_config_file calls flu_dump
aot_path_open_table calls open_config_file
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table