flu_pushinteger – Aotus
flu_pushinteger Interface
4 statements
Source File
public interface flu_pushinteger
Calls
Called by
Module Procedures
private subroutine flu_pushint(L, n)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer(kind=int_k) :: n
private subroutine flu_pushlong(L, n)
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
integer(kind=long_k) :: n
Call graph
flu_pushinteger calls flu_pushint, flu_pushlong
flu_pushint calls lua_pushinteger
flu_pushlong calls lua_pushinteger
aot_table_push calls flu_pushinteger
aot_table_set_top calls flu_pushinteger
create_1darray_double calls flu_pushinteger
create_1darray_extdouble calls flu_pushinteger
create_1darray_quadruple calls flu_pushinteger
create_1darray_real calls flu_pushinteger
set_table_double calls flu_pushinteger
set_table_extdouble calls flu_pushinteger
set_table_integer calls flu_pushinteger
set_table_logical calls flu_pushinteger
set_table_long calls flu_pushinteger
set_table_quadruple calls flu_pushinteger
set_table_real calls flu_pushinteger
set_table_string calls flu_pushinteger
set_table_userdata calls flu_pushinteger
aot_push calls aot_table_push
aot_table_from_1darray calls create_1darray_double, create_1darray_real, create_1darray_quadruple, create_1darray_extdouble
aot_table_set_val calls set_table_double, set_table_integer, set_table_logical, set_table_long, set_table_real, set_table_string, set_table_userdata, set_table_quadruple, set_table_extdouble
aot_exists calls aot_table_push
aot_fun_table calls aot_table_push
aot_reference_for calls aot_table_push
aot_table_open calls aot_table_push
aot_type_of calls aot_table_push
get_table_double calls aot_table_push
get_table_extdouble calls aot_table_push
get_table_extdouble_v calls aot_table_push
get_table_extdouble_vvect calls aot_table_push
get_table_integer calls aot_table_push
get_table_logical calls aot_table_push
get_table_long calls aot_table_push
get_table_quadruple calls aot_table_push
get_table_quadruple_v calls aot_table_push
get_table_quadruple_vvect calls aot_table_push
get_table_real calls aot_table_push
get_table_string calls aot_table_push
get_table_userdata calls aot_table_push
aot_fun_open calls aot_fun_table
aot_get_val calls get_table_quadruple_vvect, get_table_quadruple_v, get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_extdouble_vvect, get_table_extdouble_v, get_table_quadruple, get_table_extdouble, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_table_get_val calls get_table_quadruple_vvect, get_table_quadruple_v, get_table_double, get_table_integer, get_table_logical, get_table_long, get_table_real, get_table_string, get_table_userdata, get_table_extdouble_vvect, get_table_extdouble_v, get_table_quadruple, get_table_extdouble, get_table_double_vvect, get_table_integer_vvect, get_table_logical_vvect, get_table_long_vvect, get_table_real_vvect, get_table_string_vvect, get_table_double_v, get_table_integer_v, get_table_logical_v, get_table_long_v, get_table_real_v, get_table_string_v
aot_fun_put_double_v calls aot_table_from_1darray
aot_fun_put_extdouble_v calls aot_table_from_1darray
aot_fun_put_quadruple_v calls aot_table_from_1darray
aot_fun_put_single_v calls aot_table_from_1darray
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_set_val, aot_table_open
get_table_double_v calls aot_type_of
get_table_double_vvect calls aot_type_of
get_table_integer_v calls aot_type_of
get_table_integer_vvect calls aot_type_of
get_table_logical_v calls aot_type_of
get_table_logical_vvect calls aot_type_of
get_table_long_v calls aot_type_of
get_table_long_vvect calls aot_type_of
get_table_real_v calls aot_type_of
get_table_real_vvect calls aot_type_of
get_table_string_v calls aot_type_of
get_table_string_vvect calls aot_type_of
aot_fun_put calls aot_fun_put_quadruple_v, aot_fun_put_extdouble_v, aot_fun_put_double_v, aot_fun_put_single_v
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_fun_open, aot_path_open_table