flu_dump – Aotus
flu_dump Interface
3 statements
Source File
public interface flu_dump
Calls
Called by
Module Procedures
private subroutine flu_dump_toBuf(L, buf, length, iError)
Dump to a buffer and return the pointer to the resulting string.
Arguments
Type Intent Optional Attributes Name
type(flu_State) :: L
type(cbuf_type), intent(out) :: buf
integer :: length
integer :: iError
Call graph
flu_dump calls flu_dump_tobuf
flu_dump_tobuf calls dump_lua_tobuf
aot_file_to_buffer calls flu_dump
open_config_file calls flu_dump
aot_path_open_table calls open_config_file
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table