lua_pcallk – Aotus
lua_pcallk Interface
187 statements
Source File
interface
Called by
public function lua_pcallk(L, nargs, nresults, errfunc, ctx, k) bind(c, name="lua_pcallk")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
integer(kind=c_int), value :: nargs
integer(kind=c_int), value :: nresults
integer(kind=c_int), value :: errfunc
integer(kind=c_int), value :: ctx
type(c_ptr), value :: k
Return Value integer(kind=c_int)
Call graph
flu_pcall calls lua_pcallk
aot_fun_do calls flu_pcall
open_config_buffer calls flu_pcall
open_config_chunk calls flu_pcall
open_config_file calls flu_pcall
test calls flu_pcall
aot_path_open_table calls open_config_file
aot_require_buffer calls open_config_buffer
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table