lua_tolstring – Aotus
lua_tolstring Interface
187 statements
Source File
interface
Called by
public function lua_tolstring(L, index, len) bind(c, name="lua_tolstring")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
integer(kind=c_int), value :: index
integer(kind=c_size_t) :: len
Return Value type(c_ptr)
Call graph
flu_tolstring calls lua_tolstring
aot_err_handler calls flu_tolstring
aot_top_get_string calls flu_tolstring
test calls flu_tolstring
aot_top_get_val calls aot_top_get_string
aot_file_to_buffer calls aot_err_handler
aot_fun_do calls aot_err_handler
open_config_buffer calls aot_err_handler
open_config_chunk calls aot_err_handler
open_config_file calls aot_err_handler
aot_path_open_table calls open_config_file
aot_require_buffer calls open_config_buffer
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table