lua_isString – Aotus
lua_isString Interface
187 statements
Source File
interface
Called by
public function lua_isString(L, index) bind(c, name="lua_isstring")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
integer(kind=c_int), value :: index
Return Value integer(kind=c_int)
Call graph
flu_isstring calls lua_isstring
aot_top_get_string calls flu_isstring
get_top_string_vvect calls flu_isstring
aot_top_get_val calls get_top_string_vvect, aot_top_get_string