lua_pushnumber – Aotus
lua_pushnumber Interface
187 statements
Source File
interface
Called by
public subroutine lua_pushnumber(L, n) bind(c, name="lua_pushnumber")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
real(kind=c_double), value :: n
Call graph
flu_pushdouble calls lua_pushnumber
flu_pushreal calls lua_pushnumber
flu_pushnumber calls flu_pushdouble, flu_pushreal
aot_fun_put_double calls flu_pushnumber
aot_fun_put_extdouble calls flu_pushnumber
aot_fun_put_quadruple calls flu_pushnumber
aot_fun_put_single calls flu_pushnumber
create_1darray_double calls flu_pushnumber
create_1darray_extdouble calls flu_pushnumber
create_1darray_quadruple calls flu_pushnumber
create_1darray_real calls flu_pushnumber
set_table_double calls flu_pushnumber
set_table_extdouble calls flu_pushnumber
set_table_quadruple calls flu_pushnumber
set_table_real calls flu_pushnumber
aot_fun_put calls aot_fun_put_quadruple, aot_fun_put_quadruple_v, aot_fun_put_extdouble, aot_fun_put_extdouble_v, aot_fun_put_double, aot_fun_put_single, aot_fun_put_double_v, aot_fun_put_single_v
aot_table_from_1darray calls create_1darray_double, create_1darray_real, create_1darray_quadruple, create_1darray_extdouble
aot_table_set_val calls set_table_double, set_table_real, set_table_quadruple, set_table_extdouble
aot_fun_put_double_v calls aot_table_from_1darray
aot_fun_put_extdouble_v calls aot_table_from_1darray
aot_fun_put_quadruple_v calls aot_table_from_1darray
aot_fun_put_single_v calls aot_table_from_1darray
aot_require_buffer calls aot_table_set_val