lua_gettop – Aotus
lua_gettop Interface
187 statements
Source File
interface
Called by
public function lua_gettop(L) bind(c, name="lua_gettop")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
Return Value integer(kind=c_int)
Call graph
flu_gettop calls lua_gettop
aot_fun_put_top calls flu_gettop
aot_fun_top calls flu_gettop
aot_table_open calls flu_gettop, aot_table_top
aot_table_set_top calls flu_gettop
aot_table_top calls flu_gettop
create_1darray_double calls flu_gettop
create_1darray_extdouble calls flu_gettop
create_1darray_quadruple calls flu_gettop
create_1darray_real calls flu_gettop
aot_fun_put calls aot_fun_put_top, aot_fun_put_double_v, aot_fun_put_single_v, aot_fun_put_extdouble_v, aot_fun_put_quadruple_v
aot_table_from_1darray calls create_1darray_extdouble, create_1darray_double, create_1darray_real, create_1darray_quadruple
aot_fun_ref calls aot_fun_top
aot_fun_table calls aot_fun_top
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
get_top_double_v calls aot_table_top
get_top_double_vvect calls aot_table_top
get_top_extdouble_v calls aot_table_top
get_top_extdouble_vvect calls aot_table_top
get_top_integer_v calls aot_table_top
get_top_integer_vvect calls aot_table_top
get_top_logical_v calls aot_table_top
get_top_logical_vvect calls aot_table_top
get_top_long_v calls aot_table_top
get_top_long_vvect calls aot_table_top
get_top_quadruple_v calls aot_table_top
get_top_quadruple_vvect calls aot_table_top
get_top_real_v calls aot_table_top
get_top_real_vvect calls aot_table_top
get_top_string_v calls aot_table_top
get_top_string_vvect calls aot_table_top
aot_fun_open calls aot_fun_ref, aot_fun_table
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_top_get_val calls get_top_quadruple_vvect, get_top_quadruple_v, get_top_extdouble_vvect, get_top_extdouble_v, get_top_double_vvect, get_top_integer_vvect, get_top_logical_vvect, get_top_long_vvect, get_top_real_vvect, get_top_string_vvect, get_top_double_v, get_top_integer_v, get_top_logical_v, get_top_long_v, get_top_real_v, get_top_string_v
aot_fun_put_double_v calls aot_table_from_1darray
aot_fun_put_extdouble_v calls aot_table_from_1darray
aot_fun_put_quadruple_v calls aot_table_from_1darray
aot_fun_put_single_v calls aot_table_from_1darray
aot_path_open_fun calls aot_path_open_table, aot_fun_open