lua_rawgeti – Aotus
lua_rawgeti Interface
187 statements
Source File
interface
Called by
public function lua_rawgeti(L, index, n) bind(c, name="lua_rawgeti")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
integer(kind=c_int), value :: index
integer(kind=c_int), value :: n
Return Value integer(kind=c_int)
Call graph
flu_rawgeti calls lua_rawgeti
aot_reference_to_top calls flu_rawgeti
aot_fun_ref calls aot_reference_to_top
aot_fun_open calls aot_fun_ref
aot_path_open_fun calls aot_fun_open
aot_path_open calls aot_path_open_fun