lua_setfield – Aotus
lua_setfield Interface
187 statements
Source File
interface
Called by
public subroutine lua_setfield(L, index, k) bind(c, name="lua_setfield")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
integer(kind=c_int), value :: index
character(kind=c_char, len=1), dimension(*) :: k
Call graph
flu_setfield calls lua_setfield
aot_table_set_top calls flu_setfield
set_table_double calls flu_setfield
set_table_extdouble calls flu_setfield
set_table_integer calls flu_setfield
set_table_logical calls flu_setfield
set_table_long calls flu_setfield
set_table_quadruple calls flu_setfield
set_table_real calls flu_setfield
set_table_string calls flu_setfield
set_table_userdata calls flu_setfield
aot_table_set_val calls set_table_double, set_table_integer, set_table_logical, set_table_long, set_table_real, set_table_string, set_table_userdata, set_table_quadruple, set_table_extdouble
aot_require_buffer calls aot_table_set_val