lua_createtable – Aotus
lua_createtable Interface
187 statements
Source File
interface
Called by
public subroutine lua_createtable(L, narr, nrec) bind(c, name="lua_createtable")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
integer(kind=c_int), value :: narr
integer(kind=c_int), value :: nrec
Call graph
flu_createtable calls lua_createtable
aot_table_open calls flu_createtable
create_1darray_double calls flu_createtable
create_1darray_extdouble calls flu_createtable
create_1darray_quadruple calls flu_createtable
create_1darray_real calls flu_createtable
aot_table_from_1darray calls create_1darray_extdouble, create_1darray_double, create_1darray_real, create_1darray_quadruple
aot_path_open_table calls aot_table_open
aot_require_buffer calls aot_table_open
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_fun_put_double_v calls aot_table_from_1darray
aot_fun_put_extdouble_v calls aot_table_from_1darray
aot_fun_put_quadruple_v calls aot_table_from_1darray
aot_fun_put_single_v calls aot_table_from_1darray
aot_path_open_fun calls aot_path_open_table
aot_fun_put calls aot_fun_put_double_v, aot_fun_put_single_v, aot_fun_put_quadruple_v, aot_fun_put_extdouble_v