luaL_newstate – Aotus
luaL_newstate Interface
49 statements
Source File
interface
Called by
public function luaL_newstate() bind(c, name="luaL_newstate")
Arguments
None
Return Value type(c_ptr)
Call graph
flul_newstate calls lual_newstate
aot_file_to_buffer calls flul_newstate
open_config_buffer calls flul_newstate
open_config_chunk calls flul_newstate
open_config_file calls flul_newstate
test calls flul_newstate
aot_path_open_table calls open_config_file
aot_require_buffer calls open_config_buffer
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table