luaL_loadfilex – Aotus
luaL_loadfilex Interface
49 statements
Source File
interface
Called by
public function luaL_loadfilex(L, filename, mode) bind(c, name="luaL_loadfilex")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
character(kind=c_char, len=1), dimension(*) :: filename
character(kind=c_char, len=1), dimension(*) :: mode
Return Value integer(kind=c_int)
Call graph
flul_loadfile calls lual_loadfilex
aot_file_to_buffer calls flul_loadfile
open_config_file calls flul_loadfile
test calls flul_loadfile
aot_path_open_table calls open_config_file
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table