luaL_openlibs – Aotus
luaL_openlibs Interface
49 statements
Source File
interface
Called by
public subroutine luaL_openlibs(L) bind(c, name="luaL_openlibs")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: L
Call graph
flul_openlibs calls lual_openlibs
open_config_buffer calls flul_openlibs
open_config_chunk calls flul_openlibs
open_config_file calls flul_openlibs
aot_path_open_table calls open_config_file
aot_require_buffer calls open_config_buffer
aot_path_open calls aot_path_open_table, aot_path_open_fun
aot_path_open_fun calls aot_path_open_table