test – Aotus
test Program
27 statements
Source File
Uses
flu_binding
Calls
Variables
Type Attributes Name Initial
type(flu_State) :: L
character(len=89) :: filename
integer :: str_len
integer :: widthtype
integer :: heighttype
Source Code
program test
  use flu_binding
  implicit none
  type(flu_State) :: L
  character(len=89) :: filename
  integer :: str_len
  integer :: widthtype, heighttype
  L = fluL_newstate()
  filename = "config.test"
  if (fluL_loadfile(L, filename).ne.0) then
     write(*,*) "cannot load configuration file: ", flu_tolstring(L,-1, str_len)
     STOP
  endif
  if (flu_pcall(L, 0, 0, 0).ne.0) then
     write(*,*) "cannot run configuration file: ", flu_tolstring(L,-1, str_len)
     STOP
  endif
  widthtype = flu_getglobal(L, "width")
  heighttype = flu_getglobal(L, "height")
  if (widthtype == FLU_TNUMBER) then
    write(*,*) 'width=', flu_tonumber(L, -2)
  end if
  if (heighttype == FLU_TNUMBER) then
    write(*,*) 'height=', flu_tonumber(L, -1)
  end if
  call flu_close(L)
end program test
Call graph
test calls flu_close, flu_getglobal, flu_pcall, flu_tolstring, flu_tonumber, flul_loadfile, flul_newstate
flu_close calls lua_close
flu_getglobal calls lua_getglobal
flu_pcall calls lua_pcallk
flu_tolstring calls lua_tolstring
flu_tonumber calls lua_tonumberx
flul_loadfile calls lual_loadfilex
flul_newstate calls lual_newstate