name: Fordoc

on:
  push:
    branches:
      - 'branch/default'

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install FORD
        run: |
          python -m pip install --upgrade pip
          pip install ford
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build FORD Documentation
        run: |
          git_hash=$(git describe --abbrev=12 --always "$GITHUB_SHA")
          ford -r $git_hash --externalize aot_mainpage.md

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docu
